import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { SERVER_PLUS_DELIVERABLES } from './docs/serverPlusDeliverables';
import { SERVER_PLUS } from './data/seed/serverPlus';

/**
 * The starter pack is the one course artifact nobody can correct after the fact:
 * a student unzips it onto their own disk in Week 0 and reads the READMEs there.
 * It is generated by `scripts/build-starter-pack.py`, whose FOLDERS dict is hand
 * written because Python cannot import the TypeScript deliverables.
 *
 * That is exactly the shape of thing that drifts, and it did: after the forms
 * went 11 → 6 → 8, the dict still named nine deleted forms, and the folder tree
 * the platform shows in Week 0 named the same nine. These tests tie all three
 * together — the deliverables, the generator, and the in-platform tree — so the
 * next restructure fails here rather than in a student's download.
 *
 * `08_Evidence` is the one folder that is not a form: photos and screenshots.
 */

const REPO = join(__dirname, '..', '..');
const GENERATOR = join(REPO, 'scripts', 'build-starter-pack.py');
const EVIDENCE = '08_Evidence';

/** The FOLDERS keys, read out of the generator's dict literal. */
function generatorFolders(): string[] {
  const src = readFileSync(GENERATOR, 'utf-8');
  const start = src.indexOf('FOLDERS: dict[str, str] = {');
  expect(start, 'FOLDERS dict not found in the generator').toBeGreaterThan(-1);
  const body = src.slice(start, src.indexOf('\n}\n', start));
  return [...body.matchAll(/^ {4}"([^"]+)":/gm)].map((m) => m[1]);
}

/** The folder labels on the Week 0 "Unzip the starter pack" step's tree. */
function platformTreeFolders(): string[] {
  const step = SERVER_PLUS.tasks
    .flatMap((t) => t.steps ?? [])
    .find((s) => s.id === 'sp-w0-starter-s1');
  expect(step, 'sp-w0-starter-s1 has gone away').toBeDefined();
  return (step!.tree?.children ?? [])
    .filter((c) => c.kind === 'folder')
    .map((c) => c.label);
}

const deliverableFolders = SERVER_PLUS_DELIVERABLES.map((d) => d.folder);
const expected = [...deliverableFolders, EVIDENCE];

describe('Server+ deliverable folders', () => {
  it('gives every form its own folder', () => {
    expect(new Set(deliverableFolders).size).toBe(SERVER_PLUS_DELIVERABLES.length);
  });

  it('numbers each folder to match its form (prefix = num - 1)', () => {
    for (const d of SERVER_PLUS_DELIVERABLES) {
      expect(d.folder.slice(0, 2), `${d.title}: folder ${d.folder} vs num ${d.num}`).toBe(
        String(d.num - 1).padStart(2, '0'),
      );
    }
  });

  it('numbers each file to match its form', () => {
    for (const d of SERVER_PLUS_DELIVERABLES) {
      expect(d.file.slice(0, 2), `${d.title}: file ${d.file} vs num ${d.num}`).toBe(
        String(d.num).padStart(2, '0'),
      );
    }
  });

  it('leaves 08_Evidence free — it is not a form', () => {
    expect(deliverableFolders).not.toContain(EVIDENCE);
  });
});

describe('starter pack generator', () => {
  it('builds exactly the deliverable folders, plus evidence, in order', () => {
    expect(generatorFolders()).toEqual(expected);
  });

  it('names no retired form in its folder blurbs', () => {
    const src = readFileSync(GENERATOR, 'utf-8');
    const titles = SERVER_PLUS_DELIVERABLES.map((d) => d.title);
    const start = src.indexOf('FOLDERS: dict[str, str] = {');
    const body = src.slice(start, src.indexOf('\n}\n', start));
    for (const retired of RETIRED_FORM_NAMES) {
      // A retired name is only a problem if it is not a substring of a live title.
      if (titles.some((t) => t.includes(retired))) continue;
      expect(body, `generator blurb still names the retired "${retired}"`).not.toContain(retired);
    }
  });
});

describe('the folder tree the platform shows in Week 0', () => {
  it('matches the pack a student actually unzips', () => {
    expect(platformTreeFolders()).toEqual(expected);
  });
});

/**
 * Names that no Server+ form answers to any more. The cyber course really does
 * have a Change Log, so this list is only ever asserted against Server+ files.
 */
export const RETIRED_FORM_NAMES = [
  'Business Requirements Sheet',
  'Upgrade Planning Sheet',
  'Change Log',
  'Rack Plan & Cabling',
  'Server Hardware Discovery Sheet',
  'Asset Register',
  'Architecture & IP Plan',
  'Configuration Management Record',
  'Patch Management Log',
  'Disaster Recovery Plan',
  'As-Built Handover Package',
];

const SERVER_PLUS_FILES = [
  'src/lib/data/seed/serverPlus.ts',
  'src/lib/docs/serverPlusDeliverables.ts',
  'src/components/docs/ServerConfigGuide.tsx',
  'src/lib/docs/serverProcedures.ts',
  'src/components/diagrams/ServerTopologyDiagram.tsx',
];

describe('retired Server+ form names', () => {
  const liveTitles = SERVER_PLUS_DELIVERABLES.map((d) => d.title);

  it.each(SERVER_PLUS_FILES)('are gone from %s', (rel) => {
    // JSX writes "&" as "&amp;" and wraps prose across lines, so "Architecture
    // &amp;\n IP Plan" is the same drift as "Architecture & IP Plan" and has to
    // be normalised before matching — four real stale names hid behind exactly
    // that until this decode was added.
    const src = readFileSync(join(REPO, rel), 'utf-8')
      .replace(/&amp;/g, '&')
      .replace(/\s+/g, ' ');
    for (const retired of RETIRED_FORM_NAMES) {
      // "Asset Register" survives inside "Rack, Power & Asset Register"; only a
      // bare occurrence is drift, so allow the live titles through first.
      const stripped = liveTitles.reduce((acc, t) => acc.split(t).join(''), src);
      expect(stripped, `${rel} still names the retired "${retired}"`).not.toContain(retired);
    }
  });
});
