-- Capstone Quarry — complete database setup, in one file.
--
-- WHAT THIS IS
--   Every migration from supabase/migrations/, concatenated in order. Paste the
--   whole file into the Supabase dashboard once:
--
--     SQL Editor (left sidebar)  →  New query  →  paste  →  Run
--
--   Expect "Success. No rows returned." That is what success looks like for
--   statements that create things rather than select them.
--
-- WHEN TO RUN IT
--   Before the first person signs in. This installs the trigger that creates a
--   profile row for each new account; an account made before that trigger exists
--   will have no profile, and the fix is to delete the user and sign in again.
--
-- SAFE TO RE-RUN
--   Every statement is idempotent (if not exists / or replace / drop-then-create),
--   so running it twice changes nothing.
--
-- DO NOT EDIT THIS FILE
--   It is generated. Edit the files in supabase/migrations/ and re-run:
--       python3 scripts/build-setup-sql.py


-- ─── 0001_init.sql ────────────────────

-- 0001_init.sql — accounts, roster, progress and team artifacts.
--
-- This is the schema that used to live only inside SUPABASE_SETUP.md as a block
-- to copy-paste. It is the same schema, made **idempotent** so it can be re-run
-- safely: some projects were set up by pasting the markdown by hand, and a
-- second run must be a no-op rather than an error.
--
-- Every table is row-level secured. The rules, in one sentence each:
--   profiles          — you read/write your own; teammates may read your name.
--   memberships       — you write your own; anyone on the course may read it.
--   step_completions  — you write your own; teammates may read yours.
--   deliverables      — the whole team reads and writes (shared documents).
--   gate_status       — same as deliverables.
-- Instructors may additionally read (never write) the first four.

-- ── 1. profiles (1:1 with auth.users) ────────────────────────────────────────
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  is_instructor boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

drop policy if exists "profiles self read"      on public.profiles;
drop policy if exists "profiles self update"    on public.profiles;
drop policy if exists "profiles self insert"    on public.profiles;
drop policy if exists "profiles teammates read" on public.profiles;

create policy "profiles self read"   on public.profiles for select using (auth.uid() = id);
create policy "profiles self update" on public.profiles for update using (auth.uid() = id);
create policy "profiles self insert" on public.profiles for insert with check (auth.uid() = id);
-- "profiles teammates read" is created in section 2, after memberships exists:
-- a policy expression is validated when it is created, so it cannot name a
-- table that a later section creates. (Found the first time this file ran on
-- a real Postgres — see scripts/db-check.sh.)

-- auto-create a profile row on signup, so the app never has to.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email))
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users for each row execute function public.handle_new_user();

-- ── 2. memberships (roster). user_id replaces the old synthesized memberId ───
create table if not exists public.memberships (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  team_id text not null,
  role text not null,
  display_name text not null,
  cohort text not null,
  joined_at timestamptz not null default now(),
  primary key (user_id, course_id)              -- one team per user per course
);
alter table public.memberships enable row level security;

drop policy if exists "memberships self write"  on public.memberships;
drop policy if exists "memberships course read" on public.memberships;

create policy "memberships self write" on public.memberships for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "memberships course read" on public.memberships for select using (
  exists (select 1 from public.memberships me
          where me.user_id = auth.uid() and me.course_id = memberships.course_id)
);

-- teammates may read each other's display name
create policy "profiles teammates read" on public.profiles for select using (
  exists (select 1 from public.memberships m1
          join public.memberships m2
            on m1.course_id = m2.course_id and m1.team_id = m2.team_id
          where m1.user_id = auth.uid() and m2.user_id = profiles.id)
);

-- ── 3. step_completions ──────────────────────────────────────────────────────
create table if not exists public.step_completions (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  task_id text not null,
  step_id text not null,
  completed_at timestamptz not null default now(),
  primary key (user_id, course_id, task_id, step_id)
);
alter table public.step_completions enable row level security;

drop policy if exists "completions self write"     on public.step_completions;
drop policy if exists "completions teammates read" on public.step_completions;

create policy "completions self write" on public.step_completions for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "completions teammates read" on public.step_completions for select using (
  exists (select 1 from public.memberships me
          join public.memberships them
            on me.course_id = them.course_id and me.team_id = them.team_id
          where me.user_id = auth.uid()
            and them.user_id = step_completions.user_id
            and them.course_id = step_completions.course_id)
);

-- ── 4. deliverables (team-scoped form data) ──────────────────────────────────
create table if not exists public.deliverables (
  course_id text not null,
  team_id text not null,
  deliverable_id text not null,
  data jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  primary key (course_id, team_id, deliverable_id)
);
alter table public.deliverables enable row level security;

drop policy if exists "deliverables team rw" on public.deliverables;

create policy "deliverables team rw" on public.deliverables for all
  using (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = deliverables.course_id
                   and me.team_id = deliverables.team_id))
  with check (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = deliverables.course_id
                   and me.team_id = deliverables.team_id));

-- ── 5. gate_status (team-scoped) ─────────────────────────────────────────────
create table if not exists public.gate_status (
  course_id text not null,
  team_id text not null,
  gate_id int not null,
  status text not null check (status in ('locked','ready','passed')),
  updated_at timestamptz not null default now(),
  primary key (course_id, team_id, gate_id)
);
alter table public.gate_status enable row level security;

drop policy if exists "gate team rw" on public.gate_status;

create policy "gate team rw" on public.gate_status for all
  using (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = gate_status.course_id
                   and me.team_id = gate_status.team_id))
  with check (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = gate_status.course_id
                   and me.team_id = gate_status.team_id));

-- ── Instructor read-only access (for a future dashboard) ─────────────────────
drop policy if exists "instructor reads memberships"  on public.memberships;
drop policy if exists "instructor reads completions"  on public.step_completions;
drop policy if exists "instructor reads deliverables" on public.deliverables;

create policy "instructor reads memberships"  on public.memberships      for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));
create policy "instructor reads completions"  on public.step_completions for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));
create policy "instructor reads deliverables" on public.deliverables     for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── Realtime: stream teammates' changes ──────────────────────────────────────
-- `add table` errors if the table is already in the publication, so each is
-- guarded. Wrapped individually so one already-added table doesn't abort the rest.
do $$
declare t text;
begin
  foreach t in array array['step_completions','deliverables','memberships','gate_status'] loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', t);
    exception when duplicate_object then null;
    end;
  end loop;
end $$;

-- ─── 0002_student_state.sql ────────────────────

-- 0002_student_state.sql — the student data that had no cloud path.
--
-- Before this, four things lived only in localStorage, so a student who changed
-- browser or device silently lost them: where they left off, the Week-0
-- acknowledgement, their GRC registers, and their lab access details.
--
-- Each payload is already a self-contained JSON object in the app, so each table
-- stores one `data jsonb` rather than a column per field. That keeps these
-- migrations stable when a field is added to the shape later — which has
-- happened to all three at least once already.
--
-- Idempotent for the same reason as 0001.

-- ── user_course_state — resume pointer + per-course acknowledgements ─────────
-- Shape of `data`:
--   { "resume": { "week": 2, "taskId": "cb-w2", "stepId": "cb-w2-s1", "at": 172… },
--     "homeBuildAck": true }
-- Owner-only: this is a private UI pointer, of no interest to anyone else.
create table if not exists public.user_course_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, course_id)
);
alter table public.user_course_state enable row level security;

drop policy if exists "user state self rw" on public.user_course_state;

create policy "user state self rw" on public.user_course_state for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── grc_registers — team-scoped GRC workspace ───────────────────────────────
-- Team-shared like `deliverables`, and deliberately using the identical
-- membership-join policy so the two behave the same way.
create table if not exists public.grc_registers (
  course_id text not null,
  team_id text not null,
  data jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  primary key (course_id, team_id)
);
alter table public.grc_registers enable row level security;

drop policy if exists "grc team rw" on public.grc_registers;

create policy "grc team rw" on public.grc_registers for all
  using (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = grc_registers.course_id
                   and me.team_id = grc_registers.team_id))
  with check (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = grc_registers.course_id
                   and me.team_id = grc_registers.team_id));

-- ── lab_access — the student's own lab IPs, credentials and checklist ────────
-- Shape of `data`: { "values": {...}, "checks": {...}, "notes": "..." }
--
-- STRICTLY OWNER-ONLY. This is the one table in the schema that teammates
-- CANNOT read and that instructors CANNOT read, because the `notes` field
-- explicitly invites students to record lab passwords. There is no teammate
-- policy and no instructor policy here, and that omission is deliberate — do not
-- "make it consistent" with the tables above.
create table if not exists public.lab_access (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, course_id)
);
alter table public.lab_access enable row level security;

drop policy if exists "lab access self rw" on public.lab_access;

create policy "lab access self rw" on public.lab_access for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- Only the team-shared table needs to stream: the other two are single-user, so
-- there is no second party to notify, and publishing lab_access would put
-- credentials on a realtime channel for no benefit.
do $$
begin
  begin
    execute 'alter publication supabase_realtime add table public.grc_registers';
  exception when duplicate_object then null;
  end;
end $$;

-- ─── 0003_evidence_ledger.sql ────────────────────

-- 0003_evidence_ledger.sql — persist the proof of work the app already computes.
--
-- Until now a "completed" capstone was a column of self-ticked checkboxes. The
-- app computed real signals and then threw every one of them away:
--   * the student's pasted command output and whether it matched the step's
--     `verify` tokens — React state in OutputVerify, gone on unmount;
--   * the SHA-256 of each real evidence file — computed in EvidenceHasher and
--     WeekEvidencePackager, then copied to the clipboard or into a downloaded
--     zip and forgotten.
--
-- These three tables keep those signals. Together they are the difference
-- between "the student says they did it" and "here is a hashed, timestamped
-- record of what they produced" — see docs/adr/0004-content-addressed-evidence.md
-- ("self-study keeps files local; the hash + custody record is what the platform
-- owns") and ROADMAP.md Phase 1.
--
-- WHAT THIS DOES NOT CLAIM. `step_evidence` records that output matching the
-- expected tokens was pasted, hashed and timestamped by this account. It is not
-- proof a command truly ran on a real machine — the check is client-side and a
-- determined student can defeat it. It is honest self-verification with an audit
-- trail, and the UI wording must say exactly that and no more. State-reading
-- validators (roadmap Phase 2) are what would make it proof.
--
-- PRIVACY. We deliberately store the SHA-256 of the pasted output and the match
-- counts, never the raw terminal text: that text routinely carries internal IPs,
-- hostnames and sometimes credentials. The hash is still tamper-evident — ask a
-- student to re-produce the output and it must hash identically — while the
-- platform never holds the sensitive bytes. Raw text stays in the browser.
--
-- Idempotent for the same reason as 0001 and 0002.

-- ── step_evidence — per-step verification record ─────────────────────────────
-- One row per (student, step). `method` distinguishes the two ways a step can be
-- finished, which is the single most useful fact on the whole dashboard:
--   'verified-output' — pasted output contained every `verify` token
--   'self-attested'   — the student ticked the box; no matching output
--   'file-hash'       — completion evidenced by a hashed artifact
-- `attempts` counts pastes, so a step solved on the fifth try is visible as real
-- troubleshooting rather than being flattened to a tick. Effort is MEASURED AND
-- NEVER REWARDED — the rubric is not speed (see ARCHITECTURE.md §3).
--
-- Owner-only, like user_course_state. No teammate or instructor policy: this
-- round the student's verification record is private to them and leaves only via
-- the portfolio export they choose to generate.
create table if not exists public.step_evidence (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  task_id text not null,
  step_id text not null,
  verified boolean not null default false,
  method text not null default 'self-attested'
    check (method in ('verified-output', 'self-attested', 'file-hash')),
  matched_tokens int not null default 0,
  total_tokens int not null default 0,
  output_sha256 text,
  attempts int not null default 0,
  first_attempt_at timestamptz,
  verified_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, course_id, task_id, step_id)
);
alter table public.step_evidence enable row level security;

drop policy if exists "step evidence self rw" on public.step_evidence;

create policy "step evidence self rw" on public.step_evidence for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── evidence_artifacts — the content-addressed custody record ────────────────
-- Keyed by the hash itself, so re-hashing the same file is idempotent and the
-- same artifact can never be double-counted. The FILE IS NOT STORED — only its
-- hash, name, size and where it belongs. That is the whole point of ADR-0004 for
-- self-study: the student keeps the pcap, the platform keeps the proof it
-- existed, unchanged, at a point in time.
--
-- `name_ok` records whether the filename matched the course convention
-- (YYYYMMDD_TeamXX_Tool_Action.ext, validateEvidenceFileName in src/lib/utils.ts)
-- at the moment of hashing, so evidence-naming compliance is measurable.
create table if not exists public.evidence_artifacts (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  sha256 text not null,
  filename text not null,
  size_bytes bigint not null default 0,
  week int,
  deliverable_id text,
  name_ok boolean not null default false,
  hashed_at timestamptz not null default now(),
  primary key (user_id, course_id, sha256)
);
alter table public.evidence_artifacts enable row level security;

drop policy if exists "evidence artifacts self rw" on public.evidence_artifacts;

create policy "evidence artifacts self rw" on public.evidence_artifacts for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── user_paths — the career track the student is working toward ──────────────
-- The first genuinely GLOBAL per-user row in the schema: a path spans courses
-- (Security+ → CySA+ → CISSP), so unlike every other student table it is not
-- course-scoped. Note for whoever adds the next one: hydrateCourse() in
-- src/lib/data/supabaseCache.ts filters every query by course_id and therefore
-- cannot fetch this. It is loaded by hydrateUser() instead.
create table if not exists public.user_paths (
  user_id uuid primary key references auth.users(id) on delete cascade,
  path_id text not null,
  chosen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.user_paths enable row level security;

drop policy if exists "user path self rw" on public.user_paths;

create policy "user path self rw" on public.user_paths for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- Deliberately nothing here. All three tables are single-user, so there is no
-- second party to notify, and streaming a student's verification record would
-- put their evidence on a channel for no benefit — the same reasoning that keeps
-- lab_access unpublished in 0002.

-- ─── 0004_cohort_review_notes.sql ────────────────────

-- 0004_cohort_review_notes.sql — the R68 round: an instructor can see and
-- judge the cohort, a cohort has dates, and a student can keep notes on a step
-- and say "I'm stuck" where the team can see it.
--
-- WHAT THIS WIDENS. 0001 already lets an instructor read memberships,
-- step_completions and deliverables. The cohort dashboard also needs the
-- evidence ledger (verified-vs-self-attested is the single most useful column
-- it shows) and gate status, so those gain the same read-only policy. Reads
-- only, and 0003's privacy note still holds: the ledger carries hashes and
-- counts, never pasted text.
--
-- TWO TABLES FOR NOTES, ON PURPOSE. A student's note is private (like
-- lab_access: no teammate or instructor policy). The one bit of it teammates
-- and the instructor may see is that they are stuck. RLS is row-level, so a
-- column that must hide from teammates cannot live in a row they may read —
-- hence `step_notes` (owner-only) and `step_flags` (team + instructor read).
-- The app writes both from one save and presents one record.
--
-- Idempotent for the same reason as 0001–0003.

-- ── Instructor reads the ledger and gates ────────────────────────────────────
drop policy if exists "instructor reads step evidence" on public.step_evidence;
drop policy if exists "instructor reads artifacts"     on public.evidence_artifacts;
drop policy if exists "instructor reads gates"         on public.gate_status;

create policy "instructor reads step evidence" on public.step_evidence      for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));
create policy "instructor reads artifacts"     on public.evidence_artifacts for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));
create policy "instructor reads gates"         on public.gate_status        for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── deliverable_reviews — one verdict per (team, form, week) ────────────────
create table if not exists public.deliverable_reviews (
  course_id text not null,
  team_id text not null,
  deliverable_id text not null,
  week int not null,
  status text not null check (status in ('approved', 'revise', 'pending')),
  comment text not null default '',
  reviewer text not null default '',
  reviewer_id uuid references auth.users(id),
  reviewed_at timestamptz not null default now(),
  primary key (course_id, team_id, deliverable_id, week)
);
alter table public.deliverable_reviews enable row level security;

drop policy if exists "reviews team read"       on public.deliverable_reviews;
drop policy if exists "reviews instructor all"  on public.deliverable_reviews;

create policy "reviews team read" on public.deliverable_reviews for select
  using (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = deliverable_reviews.course_id
                   and me.team_id = deliverable_reviews.team_id));
create policy "reviews instructor all" on public.deliverable_reviews for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── cohorts — the one date everything is derived from ────────────────────────
create table if not exists public.cohorts (
  course_id text not null,
  cohort text not null,
  starts_on date not null,
  set_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  primary key (course_id, cohort)
);
alter table public.cohorts enable row level security;

drop policy if exists "cohorts anyone reads"     on public.cohorts;
drop policy if exists "cohorts instructor writes" on public.cohorts;

create policy "cohorts anyone reads" on public.cohorts for select using (auth.uid() is not null);
create policy "cohorts instructor writes" on public.cohorts for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── step_notes — OWNER-ONLY, like lab_access ─────────────────────────────────
create table if not exists public.step_notes (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  task_id text not null,
  step_id text not null,
  note text not null default '',
  updated_at timestamptz not null default now(),
  primary key (user_id, course_id, task_id, step_id)
);
alter table public.step_notes enable row level security;

drop policy if exists "step_notes self rw" on public.step_notes;
create policy "step_notes self rw" on public.step_notes for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── step_flags — the shareable half ──────────────────────────────────────────
create table if not exists public.step_flags (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  task_id text not null,
  step_id text not null,
  stuck boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, course_id, task_id, step_id)
);
alter table public.step_flags enable row level security;

drop policy if exists "step_flags self rw"         on public.step_flags;
drop policy if exists "step_flags team read"       on public.step_flags;
drop policy if exists "step_flags instructor read" on public.step_flags;

create policy "step_flags self rw" on public.step_flags for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "step_flags team read" on public.step_flags for select
  using (exists (select 1 from public.memberships me
                 join public.memberships them on them.course_id = me.course_id and them.team_id = me.team_id
                 where me.user_id = auth.uid()
                   and them.user_id = step_flags.user_id
                   and me.course_id = step_flags.course_id));
create policy "step_flags instructor read" on public.step_flags for select
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- Reviews reach the team, flags reach the team, a cohort date reaches the class.
-- step_notes is deliberately absent: owner-only data has no second party.
do $$
declare t text;
begin
  foreach t in array array['deliverable_reviews','step_flags','cohorts'] loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', t);
    exception when duplicate_object then null;
    end;
  end loop;
end $$;

-- ─── 0005_course_documents.sql ────────────────────

-- 0005_course_documents.sql — the R78-D round: the course document has a table.
--
-- WHAT THIS ADDS. Every table before this one holds student state; course
-- CONTENT — the seeds and anything an instructor authored in the studio — lived
-- only in the browser's localStorage, so an authored course existed on one
-- device. `course_documents` holds one row per course: the whole document the
-- app renders from (`content/courses/<id>.json` has the same shape), keyed by
-- course id. A row with a seed's id overrides that seed, which is how the studio
-- already worked locally.
--
-- WHO SEES IT. Any signed-in user reads (the catalogue and the course pages
-- need it); only an instructor writes, using the predicate 0004 established
-- for `deliverable_reviews` and `cohorts`.
--
-- TWO REPAIRS, while a migration is open:
--   * `step_evidence.method` allowed 'file-hash', a value the app never wrote —
--     `EvidenceMethod` is 'verified-output' | 'self-attested'. The CHECK now
--     says what the type says.
--   * `grc_registers` had no reader and no writer in the app (its localStorage
--     key was never used either), only a realtime subscription. Dropped.
--
-- Idempotent for the same reason as 0001–0004.

-- ── course_documents — one row per course, the document the app renders ─────
create table if not exists public.course_documents (
  course_id text primary key,
  schema text not null,
  doc jsonb not null,
  version int not null default 1,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);
alter table public.course_documents enable row level security;

drop policy if exists "course documents signed-in read"    on public.course_documents;
drop policy if exists "course documents instructor writes" on public.course_documents;

create policy "course documents signed-in read" on public.course_documents for select
  using (auth.uid() is not null);
create policy "course documents instructor writes" on public.course_documents for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── step_evidence.method — the CHECK matches EvidenceMethod ─────────────────
alter table public.step_evidence drop constraint if exists step_evidence_method_check;
alter table public.step_evidence
  add constraint step_evidence_method_check check (method in ('verified-output', 'self-attested'));

-- ── grc_registers — nothing reads it, nothing writes it ─────────────────────
-- Dropping the table removes it from the realtime publication as well.
drop table if exists public.grc_registers;

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- A course an instructor publishes or edits should reach every open client.
do $$
begin
  begin
    execute 'alter publication supabase_realtime add table public.course_documents';
  exception when duplicate_object then null;
  end;
end $$;

-- ─── 0006_accounts.sql ────────────────────

-- 0006_accounts.sql — the R81 round: every student has an account, and the
-- team can see each other's progress and badges.
--
-- WHAT THIS FIXES. This schema was written without a project to run it on
-- (docs/OPERATIONS.md §0). The first time it ran on a real Postgres
-- (scripts/db-check.sh) the first team join failed:
--
--   ERROR: infinite recursion detected in policy for relation "memberships"
--
-- "memberships course read" subqueried `memberships` from inside a policy ON
-- `memberships`, and every teammate policy on the other tables subqueried
-- `memberships` too, so each of them re-entered the same policy. Postgres
-- accepts that at CREATE POLICY time and only fails at the first SELECT.
--
-- THE FIX is the standard one: the membership question is asked by a small
-- `security definer` function. It runs as the function's owner, so RLS on the
-- table it reads is not re-applied inside it, and there is nothing to recurse
-- into. Four questions cover every policy in the schema:
--
--   is_instructor()                 the caller's profile has the flag
--   shares_course(course)           the caller has a membership on the course
--   on_team(course, team)           the caller's membership is that team
--   same_team_as(other, course)     the caller and `other` share a team
--                                   (course null = on any course)
--
-- Each is STABLE (one evaluation per row set), has a fixed `search_path`
-- (so nobody can shadow `memberships` in a schema of their own), and is callable
-- by the request roles only. Every policy below is re-created to call them;
-- WHO CAN READ WHAT DOES NOT CHANGE, except for the one widening after it.
--
-- WHAT THIS WIDENS. `step_evidence` becomes readable by TEAMMATES (it was
-- owner + instructor). A task's gem rarity is derived from it — verified output
-- vs a self-attested tick, and whether it was on time — and the team page shows
-- each teammate's gems. 0003's privacy note still holds: the row carries a hash
-- and counts, never the pasted text, so a teammate learns "verified" or "ticked",
-- nothing about the machine. `lab_access`, `step_notes`, `user_course_state`,
-- `evidence_artifacts` and `user_paths` stay owner-only (+ instructor where 0004
-- said so).
--
-- WHAT THIS ADDS. `profiles.avatar_url`, and a signup trigger that reads the
-- name and picture Google and GitHub put in `raw_user_meta_data` (they use
-- different keys: Google `full_name`/`name`, GitHub `user_name`/
-- `preferred_username`; both `avatar_url`), falling back to the local part of
-- the email rather than the whole address.
--
-- The mine's "weeks already played" pointer moves into `user_course_state.data`
-- as `mineSeen` — jsonb, so no schema change.
--
-- Idempotent for the same reason as 0001–0005.

-- ── 1. The four membership questions ────────────────────────────────────────
create or replace function public.is_instructor()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor)
$$;

create or replace function public.shares_course(c text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.memberships m where m.user_id = auth.uid() and m.course_id = c)
$$;

create or replace function public.on_team(c text, t text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.memberships m
                 where m.user_id = auth.uid() and m.course_id = c and m.team_id = t)
$$;

create or replace function public.same_team_as(other uuid, c text default null)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.memberships me
                 join public.memberships them
                   on them.course_id = me.course_id and them.team_id = me.team_id
                 where me.user_id = auth.uid()
                   and them.user_id = other
                   and (c is null or me.course_id = c))
$$;

revoke execute on function public.is_instructor()            from public;
revoke execute on function public.shares_course(text)        from public;
revoke execute on function public.on_team(text, text)        from public;
revoke execute on function public.same_team_as(uuid, text)   from public;
grant  execute on function public.is_instructor()            to anon, authenticated, service_role;
grant  execute on function public.shares_course(text)        to anon, authenticated, service_role;
grant  execute on function public.on_team(text, text)        to anon, authenticated, service_role;
grant  execute on function public.same_team_as(uuid, text)   to anon, authenticated, service_role;

-- ── 2. Every policy that asked the membership question, re-created ──────────
-- profiles: teammates (on any course) read each other's name and picture.
drop policy if exists "profiles teammates read" on public.profiles;
create policy "profiles teammates read" on public.profiles for select
  using (public.same_team_as(id));

-- memberships: the roster is visible to everyone on the course; the instructor
-- sees every course.
drop policy if exists "memberships course read"      on public.memberships;
drop policy if exists "instructor reads memberships" on public.memberships;
create policy "memberships course read"      on public.memberships for select using (public.shares_course(course_id));
create policy "instructor reads memberships" on public.memberships for select using (public.is_instructor());

-- step_completions: teammates and the instructor read.
drop policy if exists "completions teammates read" on public.step_completions;
drop policy if exists "instructor reads completions" on public.step_completions;
create policy "completions teammates read"  on public.step_completions for select using (public.same_team_as(user_id, course_id));
create policy "instructor reads completions" on public.step_completions for select using (public.is_instructor());

-- deliverables + gate_status: the team reads and writes; the instructor reads.
drop policy if exists "deliverables team rw"          on public.deliverables;
drop policy if exists "instructor reads deliverables" on public.deliverables;
create policy "deliverables team rw" on public.deliverables for all
  using (public.on_team(course_id, team_id)) with check (public.on_team(course_id, team_id));
create policy "instructor reads deliverables" on public.deliverables for select using (public.is_instructor());

drop policy if exists "gate team rw"           on public.gate_status;
drop policy if exists "instructor reads gates" on public.gate_status;
create policy "gate team rw" on public.gate_status for all
  using (public.on_team(course_id, team_id)) with check (public.on_team(course_id, team_id));
create policy "instructor reads gates" on public.gate_status for select using (public.is_instructor());

-- step_evidence: owner writes (0003); TEAMMATES read (new); instructor reads.
drop policy if exists "step evidence team read"        on public.step_evidence;
drop policy if exists "instructor reads step evidence" on public.step_evidence;
create policy "step evidence team read"        on public.step_evidence for select using (public.same_team_as(user_id, course_id));
create policy "instructor reads step evidence" on public.step_evidence for select using (public.is_instructor());

-- evidence_artifacts: owner (0003) + instructor.
drop policy if exists "instructor reads artifacts" on public.evidence_artifacts;
create policy "instructor reads artifacts" on public.evidence_artifacts for select using (public.is_instructor());

-- deliverable_reviews: the team reads its verdicts; the instructor writes them.
drop policy if exists "reviews team read"      on public.deliverable_reviews;
drop policy if exists "reviews instructor all" on public.deliverable_reviews;
create policy "reviews team read"      on public.deliverable_reviews for select using (public.on_team(course_id, team_id));
create policy "reviews instructor all" on public.deliverable_reviews for all
  using (public.is_instructor()) with check (public.is_instructor());

-- cohorts: anyone signed in reads (0004); the instructor writes.
drop policy if exists "cohorts instructor writes" on public.cohorts;
create policy "cohorts instructor writes" on public.cohorts for all
  using (public.is_instructor()) with check (public.is_instructor());

-- step_flags: owner writes (0004); teammates and the instructor read.
drop policy if exists "step_flags team read"       on public.step_flags;
drop policy if exists "step_flags instructor read" on public.step_flags;
create policy "step_flags team read"       on public.step_flags for select using (public.same_team_as(user_id, course_id));
create policy "step_flags instructor read" on public.step_flags for select using (public.is_instructor());

-- course_documents: anyone signed in reads (0005); the instructor writes.
drop policy if exists "course documents instructor writes" on public.course_documents;
create policy "course documents instructor writes" on public.course_documents for all
  using (public.is_instructor()) with check (public.is_instructor());

-- ── 3. profiles: the picture, and a signup trigger that knows both providers ─
alter table public.profiles add column if not exists avatar_url text;

-- THE HOLE THE HARNESS FOUND. "profiles self update" (0001) lets a user update
-- their own row — and `is_instructor` is a column on that row, so any student
-- could promote themselves and read the whole class. A row policy cannot say
-- "except this column"; a column grant can. The request roles may now update
-- only the two columns a person legitimately owns. The flag is still set the
-- way SUPABASE_SETUP.md says: in the SQL editor, as the project owner.
revoke update on public.profiles from anon, authenticated;
grant  update (display_name, avatar_url) on public.profiles to authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  meta jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(
      nullif(meta->>'full_name', ''),           -- Google
      nullif(meta->>'name', ''),                -- Google, GitHub (when public)
      nullif(meta->>'user_name', ''),           -- GitHub login
      nullif(meta->>'preferred_username', ''),  -- GitHub login (OIDC shape)
      nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
      'Student'
    ),
    nullif(meta->>'avatar_url', '')
  )
  on conflict (id) do update
    set avatar_url = coalesce(public.profiles.avatar_url, excluded.avatar_url);
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users for each row execute function public.handle_new_user();

-- ─── 0007_evidence_realtime.sql ────────────────────

-- 0007_evidence_realtime.sql — teammates' gems arrive live.
--
-- 0006 made `step_evidence` readable by teammates: the gems on the team table
-- are derived from it (verified vs self-attested, on time). But the table was
-- never added to the realtime publication, so a teammate's freshly earned gem
-- only appeared when some OTHER table happened to change, or on reload. One
-- statement, same duplicate_object guard as 0001/0004/0005.
--
-- Idempotent for the same reason as 0001–0006. Already ran setup.sql? Paste
-- this file alone, or re-run all of setup.sql — every statement in it is safe
-- to run twice.
do $$
begin
  begin
    execute 'alter publication supabase_realtime add table public.step_evidence';
  exception when duplicate_object then null;
  end;
end $$;

-- ─── 0008_task_reports.sql ────────────────────

-- 0008_task_reports.sql — a "Report an issue" button on every task (R83).
--
-- WHAT THIS IS. A student stuck on unclear wording, a broken command, a lab
-- problem, a question, or content that no longer matches the tools can file a
-- structured report from inside the task. Teammates see that a report exists
-- (so they don't file duplicates); the instructor sees every report on the
-- cohort dashboard, grouped by task, and resolves it there.
--
-- WHO SEES WHAT. The reporter owns the row; teammates read it (same predicate
-- as step_flags — a report is about the shared work, not a private note); the
-- instructor reads everything and is the only one who can resolve. All
-- policies go through the 0006 security-definer helpers — never a subquery on
-- memberships/profiles (the recursion 0006 fixed; a page-shape guard enforces
-- this for every migration from 0006 on).
--
-- Idempotent for the same reason as 0001–0007.

create table if not exists public.task_reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  task_id text not null,
  team_id text not null,
  kind text not null default 'question'
    check (kind in ('unclear', 'broken', 'environment', 'question', 'outdated')),
  note text not null default '',
  status text not null default 'open' check (status in ('open', 'resolved')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id)
);
alter table public.task_reports enable row level security;

drop policy if exists "task reports self insert"     on public.task_reports;
drop policy if exists "task reports self read"       on public.task_reports;
drop policy if exists "task reports team read"       on public.task_reports;
drop policy if exists "task reports instructor read" on public.task_reports;
drop policy if exists "task reports instructor update" on public.task_reports;

create policy "task reports self insert" on public.task_reports for insert
  with check (auth.uid() = user_id);
create policy "task reports self read" on public.task_reports for select
  using (auth.uid() = user_id);
create policy "task reports team read" on public.task_reports for select
  using (public.same_team_as(user_id, course_id));
create policy "task reports instructor read" on public.task_reports for select
  using (public.is_instructor());
-- Resolution is the instructor's verdict; the reporter withdraws by talking to
-- them, which keeps the record honest.
create policy "task reports instructor update" on public.task_reports for update
  using (public.is_instructor()) with check (public.is_instructor());

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- A filed report should reach the team's rows and the instructor's dashboard
-- without a reload.
do $$
begin
  begin
    execute 'alter publication supabase_realtime add table public.task_reports';
  exception when duplicate_object then null;
  end;
end $$;

-- ─── 0009_evidence_bundles.sql ────────────────────

-- 0009_evidence_bundles.sql — immutable submissions and blind peer review (R84).
--
-- WHAT THIS IS. A team member submits a deliverable once its four rubric
-- categories are green: the submission FREEZES a snapshot (form data, the
-- validator results, the category booleans, a sha256 of the content) as an
-- append-only row. The platform then assigns the submission to two reviewers
-- from OTHER teams in the same course and cohort, chosen deterministically, who
-- answer a short binary questionnaire without ever learning whose work it is.
-- Verdicts are never stored — the app derives them (`verdictOf`) from the frozen
-- categories, the reviews, and the instructor's `deliverable_reviews` override,
-- so there is no state machine to desync.
--
-- WHO SEES WHAT.
--   deliverable_submissions — the submitting team and the instructor read;
--     anyone on the team inserts their own; NOBODY updates (trigger raises).
--     Reviewers never touch this table: they read through `get_review_packet`,
--     which strips team_id and submitted_by. Deletes have no policy — no
--     client role can delete — but stay possible for `on delete cascade` when
--     an account is erased, which an UPDATE trigger must not block.
--   peer_review_assignments — the reviewer reads their own; instructor all.
--     Writes only through `assign_peer_reviews` (security definer).
--   peer_reviews — the reviewer reads their own; instructor all. Writes only
--     through `submit_peer_review`; the primary key makes a review final.
--   The submitting team follows progress through `get_submission_progress`,
--   which returns COUNTS — never who is reviewing.
--
-- All policies use the 0006 definer helpers or same-row predicates — never a
-- subquery on memberships/profiles (the recursion 0006 fixed; guarded).
--
-- HONESTY. Same stance as 0003: the snapshot proves what was in the form and
-- what the checks said at submission time — hashes, timestamps and blind
-- review, not surveillance or cryptographic proof of who typed.
--
-- Idempotent for the same reason as 0001–0008.

create table if not exists public.deliverable_submissions (
  id uuid primary key default gen_random_uuid(),
  course_id text not null,
  team_id text not null,
  deliverable_id text not null,
  week int not null,
  version int not null default 1,
  submitted_by uuid not null references auth.users(id) on delete cascade,
  content_sha256 text not null,
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  unique (course_id, team_id, deliverable_id, week, version)
);
alter table public.deliverable_submissions enable row level security;

drop policy if exists "submissions team insert"     on public.deliverable_submissions;
drop policy if exists "submissions team read"       on public.deliverable_submissions;
drop policy if exists "submissions instructor read" on public.deliverable_submissions;

create policy "submissions team insert" on public.deliverable_submissions for insert
  with check (submitted_by = auth.uid() and public.on_team(course_id, team_id));
create policy "submissions team read" on public.deliverable_submissions for select
  using (public.on_team(course_id, team_id));
create policy "submissions instructor read" on public.deliverable_submissions for select
  using (public.is_instructor());

-- Append-only, enforced below RLS too: even a role that could write rows
-- cannot rewrite history. A new version is a new row.
create or replace function public.forbid_submission_update()
returns trigger language plpgsql as $$
begin
  raise exception 'deliverable_submissions is append-only — submit a new version instead';
end $$;
drop trigger if exists deliverable_submissions_immutable on public.deliverable_submissions;
create trigger deliverable_submissions_immutable
  before update on public.deliverable_submissions
  for each row execute function public.forbid_submission_update();

create table if not exists public.peer_review_assignments (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.deliverable_submissions(id) on delete cascade,
  reviewer_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (submission_id, reviewer_id)
);
alter table public.peer_review_assignments enable row level security;

drop policy if exists "assignments own read"        on public.peer_review_assignments;
drop policy if exists "assignments instructor read" on public.peer_review_assignments;

create policy "assignments own read" on public.peer_review_assignments for select
  using (reviewer_id = auth.uid());
create policy "assignments instructor read" on public.peer_review_assignments for select
  using (public.is_instructor());
-- No insert/update/delete policies: `assign_peer_reviews` is the only writer.

-- `submission_id` is denormalised in on purpose: the submitting team may read
-- these rows (that is how the verdict banner flips live) but must never read
-- the assignment that would name the reviewer — so the row itself has to say
-- which submission it judges, and carries no reviewer column at all.
create table if not exists public.peer_reviews (
  assignment_id uuid primary key references public.peer_review_assignments(id) on delete cascade,
  submission_id uuid not null references public.deliverable_submissions(id) on delete cascade,
  answers jsonb not null,
  confirm boolean not null,
  created_at timestamptz not null default now()
);
alter table public.peer_reviews enable row level security;

drop policy if exists "peer reviews own read"        on public.peer_reviews;
drop policy if exists "peer reviews team read"       on public.peer_reviews;
drop policy if exists "peer reviews instructor read" on public.peer_reviews;

create policy "peer reviews own read" on public.peer_reviews for select
  using (exists (select 1 from public.peer_review_assignments a
                 where a.id = assignment_id and a.reviewer_id = auth.uid()));
-- The submitting team reads the verdict rows (anonymous by construction); the
-- subquery runs under the caller's own RLS, which serves exactly their team's
-- submissions.
create policy "peer reviews team read" on public.peer_reviews for select
  using (exists (select 1 from public.deliverable_submissions s
                 where s.id = submission_id and public.on_team(s.course_id, s.team_id)));
create policy "peer reviews instructor read" on public.peer_reviews for select
  using (public.is_instructor());
-- No insert/update/delete policies: `submit_peer_review` is the only writer.

-- ── The four review verbs, as security-definer functions ────────────────────
-- The 0006 pattern: fixed search_path, revoke from public, grant to the
-- request roles. Definer, because the rows they touch are deliberately
-- unreachable by the callers' own policies (blindness cuts both ways).

-- Deterministically assign a submission to (up to) two reviewers from OTHER
-- teams of the same course and cohort — both attendance modes, ordered by
-- md5(submission || user) so the pick is stable and ungameable-by-refresh.
-- The cohort is the leading YYYY-MM of the team id (splitting on '-' would
-- return just the year). Returns how many reviewers were ELIGIBLE — fewer
-- than 2 tells the app this submission takes the platform-verdict path.
create or replace function public.assign_peer_reviews(p_submission uuid)
returns integer language plpgsql volatile security definer set search_path = public as $$
declare
  s record;
  v_cohort text;
  v_eligible integer;
begin
  select * into s from public.deliverable_submissions where id = p_submission;
  if s.id is null then
    raise exception 'no such submission';
  end if;
  if not public.on_team(s.course_id, s.team_id) then
    raise exception 'not your team''s submission';
  end if;
  v_cohort := substring(s.team_id from '^\d{4}-\d{2}');

  select count(*) into v_eligible from (
    select distinct m.user_id from public.memberships m
    where m.course_id = s.course_id
      and m.team_id <> s.team_id
      and substring(m.team_id from '^\d{4}-\d{2}') = v_cohort
  ) c;

  insert into public.peer_review_assignments (submission_id, reviewer_id)
  select p_submission, c.user_id from (
    select distinct m.user_id from public.memberships m
    where m.course_id = s.course_id
      and m.team_id <> s.team_id
      and substring(m.team_id from '^\d{4}-\d{2}') = v_cohort
  ) c
  order by md5(p_submission::text || c.user_id::text)
  limit 2
  on conflict (submission_id, reviewer_id) do nothing;

  return v_eligible;
end $$;

-- The reviewer's queue: what to review, never whose it is.
create or replace function public.get_review_queue()
returns table (assignment_id uuid, course_id text, deliverable_id text, week int,
               assigned_at timestamptz, done boolean)
language sql stable security definer set search_path = public as $$
  select a.id, s.course_id, s.deliverable_id, s.week, a.created_at,
         exists (select 1 from public.peer_reviews r where r.assignment_id = a.id)
  from public.peer_review_assignments a
  join public.deliverable_submissions s on s.id = a.submission_id
  where a.reviewer_id = auth.uid()
  order by a.created_at
$$;

-- One assignment's packet: the frozen snapshot with the identifying keys
-- stripped, and no team_id/submitted_by columns selected at all.
create or replace function public.get_review_packet(p_assignment uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'assignmentId',  a.id,
    'courseId',      s.course_id,
    'deliverableId', s.deliverable_id,
    'week',          s.week,
    'version',       s.version,
    'contentSha256', s.content_sha256,
    'snapshot',      (s.snapshot - 'teamId') - 'submittedBy',
    'submittedAt',   s.created_at
  )
  from public.peer_review_assignments a
  join public.deliverable_submissions s on s.id = a.submission_id
  where a.id = p_assignment and a.reviewer_id = auth.uid()
$$;

-- One review per assignment, by its assignee, final on insert (the pk).
create or replace function public.submit_peer_review(p_assignment uuid, p_answers jsonb, p_confirm boolean)
returns void language plpgsql volatile security definer set search_path = public as $$
declare v_submission uuid;
begin
  select a.submission_id into v_submission from public.peer_review_assignments a
    where a.id = p_assignment and a.reviewer_id = auth.uid();
  if v_submission is null then
    raise exception 'not your assignment';
  end if;
  insert into public.peer_reviews (assignment_id, submission_id, answers, confirm)
  values (p_assignment, v_submission, p_answers, p_confirm);
end $$;

-- The submitting team's (and instructor's) progress view: counts and the
-- confirm tally — never reviewer identities.
create or replace function public.get_submission_progress(p_submission uuid)
returns table (assigned integer, reviewed integer, confirms integer)
language sql stable security definer set search_path = public as $$
  select count(a.id)::int,
         count(r.assignment_id)::int,
         count(*) filter (where r.confirm)::int
  from public.deliverable_submissions s
  left join public.peer_review_assignments a on a.submission_id = s.id
  left join public.peer_reviews r on r.assignment_id = a.id
  where s.id = p_submission
    and (public.on_team(s.course_id, s.team_id) or public.is_instructor())
$$;

revoke execute on function public.assign_peer_reviews(uuid)                 from public;
revoke execute on function public.get_review_queue()                        from public;
revoke execute on function public.get_review_packet(uuid)                   from public;
revoke execute on function public.submit_peer_review(uuid, jsonb, boolean)  from public;
revoke execute on function public.get_submission_progress(uuid)             from public;
grant  execute on function public.assign_peer_reviews(uuid)                 to authenticated, service_role;
grant  execute on function public.get_review_queue()                        to authenticated, service_role;
grant  execute on function public.get_review_packet(uuid)                   to authenticated, service_role;
grant  execute on function public.submit_peer_review(uuid, jsonb, boolean)  to authenticated, service_role;
grant  execute on function public.get_submission_progress(uuid)             to authenticated, service_role;

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- A submission should reach teammates' pages, and a finished review should
-- reach the submitting team's verdict banner, without a reload.
do $$
begin
  begin
    execute 'alter publication supabase_realtime add table public.deliverable_submissions';
  exception when duplicate_object then null;
  end;
  begin
    execute 'alter publication supabase_realtime add table public.peer_reviews';
  exception when duplicate_object then null;
  end;
end $$;

-- ─── 0010_admin_and_roster.sql ────────────────────

-- 0010_admin_and_roster.sql — two staff roles, and a roster someone can fix (R85).
--
-- WHAT THIS IS. Until now the platform had one staff flag, `is_instructor`,
-- and it did two unrelated jobs: running the class (grading, cohort dates,
-- resolving reports) AND owning the content (writing course documents). This
-- migration splits them:
--
--   instructor — runs the class: sees every student, team and submission,
--                grades, resolves reports, sets cohort dates, and can now
--                FIX THE ROSTER (move a student between teams, change their
--                role, remove them from a course).
--   admin      — owns the platform: everything an instructor can do, PLUS
--                writing course documents (the Studio: course structure,
--                deliverable definitions, reference content).
--
-- HOW ADMIN INHERITS. `public.is_instructor()` now answers true for admins
-- too (`is_instructor OR is_admin`), so every instructor policy from
-- 0001–0009 covers admins with no policy churn — one definition, not thirty
-- edits. `public.is_admin()` exists for the few places that are admin-only.
--
-- WHAT ELSE THIS FIXES. An instructor with no team membership could read only
-- their OWN profile row — so the cohort dashboard could not put a name or a
-- picture next to a single student. Instructors now read all profiles, which
-- carry a display name and an avatar URL and nothing else (grades, notes and
-- credentials live in other tables with their own rules).
--
-- Granting either flag is an operator action in the SQL Editor (documented in
-- SUPABASE_SETUP.md); students cannot set either on themselves — the 0006
-- column grant already limits their UPDATE to display_name and avatar_url,
-- and this migration re-asserts it now that a second privileged column exists.
--
-- Idempotent for the same reason as 0001–0009.

-- ── 1. The admin flag and the two helpers ───────────────────────────────────
alter table public.profiles add column if not exists is_admin boolean not null default false;

-- Re-assert the column grants (0006): request roles update ONLY the two
-- columns a person owns. `is_admin` is covered by the same revoke.
revoke update on public.profiles from anon, authenticated;
grant  update (display_name, avatar_url) on public.profiles to authenticated;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin)
$$;

-- Admins ARE instructors everywhere the platform asks: one definition covers
-- every instructor policy written since 0001.
create or replace function public.is_instructor()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles p
                 where p.id = auth.uid() and (p.is_instructor or p.is_admin))
$$;

revoke execute on function public.is_admin() from public;
grant  execute on function public.is_admin() to anon, authenticated, service_role;

-- ── 2. Instructors read every profile (name + picture, nothing else) ───────
drop policy if exists "profiles instructor read" on public.profiles;
create policy "profiles instructor read" on public.profiles for select
  using (public.is_instructor());

-- ── 3. Content belongs to admins ────────────────────────────────────────────
-- The Studio's write path. Read stays signed-in (0005); grading, reports,
-- cohorts and everything else instructors do is untouched.
drop policy if exists "course documents instructor writes" on public.course_documents;
drop policy if exists "course documents admin writes"      on public.course_documents;
create policy "course documents admin writes" on public.course_documents for all
  using (public.is_admin()) with check (public.is_admin());

-- ── 4. Instructors manage the roster ────────────────────────────────────────
-- Students still join and leave themselves ("memberships self write", 0001).
-- What was impossible was CORRECTING a roster: a student on the wrong team,
-- a wrong role, someone who left the class. Update and delete only — an
-- instructor never enrols someone who didn't sign up themselves.
drop policy if exists "memberships instructor manage" on public.memberships;
drop policy if exists "memberships instructor remove" on public.memberships;
create policy "memberships instructor manage" on public.memberships for update
  using (public.is_instructor()) with check (public.is_instructor());
create policy "memberships instructor remove" on public.memberships for delete
  using (public.is_instructor());

-- ─── 0011_agreement_log.sql ────────────────────

-- 0011_agreement_log.sql — the acknowledgement log, and a last-seen clock (R86).
--
-- WHAT THIS IS. Before using the platform every account acknowledges the
-- click-through agreements (terms/no-exam-guarantee, acceptable use, lab
-- responsibility, data notice, conduct — the registry in
-- src/lib/legal/agreements.ts). This table is the LOG of those clicks: one
-- append-only row per (user, agreement, version), so the record says exactly
-- which text a person agreed to and when, and a version bump makes the gate
-- ask again without erasing what they agreed to before.
--
-- WHO SEES WHAT. A person inserts and reads their own rows; instructors and
-- admins read everyone's (the metrics view shows who has signed what).
-- NOBODY updates or deletes — an acknowledgement is history, and disagreeing
-- later is an account-deletion conversation, not an edit.
--
-- ALSO HERE: profiles.last_seen_at — the small clock behind "who is on the
-- platform right now / when were they last active" on the admin metrics page.
-- The app updates the caller's OWN column on a throttled heartbeat; the 0006
-- column grant is re-issued to allow exactly the three self-owned columns.
--
-- Idempotent for the same reason as 0001–0010.

create table if not exists public.agreement_acceptances (
  user_id uuid not null references auth.users(id) on delete cascade,
  agreement_id text not null,
  version int not null,
  accepted_at timestamptz not null default now(),
  primary key (user_id, agreement_id, version)
);
alter table public.agreement_acceptances enable row level security;

drop policy if exists "acceptances self insert"     on public.agreement_acceptances;
drop policy if exists "acceptances self read"       on public.agreement_acceptances;
drop policy if exists "acceptances instructor read" on public.agreement_acceptances;

create policy "acceptances self insert" on public.agreement_acceptances for insert
  with check (auth.uid() = user_id);
create policy "acceptances self read" on public.agreement_acceptances for select
  using (auth.uid() = user_id);
create policy "acceptances instructor read" on public.agreement_acceptances for select
  using (public.is_instructor());
-- No update or delete policies: the log only ever grows.

-- ── last activity ───────────────────────────────────────────────────────────
alter table public.profiles add column if not exists last_seen_at timestamptz;

revoke update on public.profiles from anon, authenticated;
grant  update (display_name, avatar_url, last_seen_at) on public.profiles to authenticated;

-- ─── 0012_deliverable_lifecycle.sql ────────────────────

-- 0012_deliverable_lifecycle.sql — the document lifecycle (R103).
--
-- WHAT THIS IS. A deliverable is a document in an organisation: one role
-- drafts it, another reviews it, a third approves it, and then it is issued
-- to whoever consumes it. This table is the team's own record of that
-- movement: one append-only row per transition (draft → in_review →
-- approved → issued, or a return to draft with a reason). The current state
-- of a form is its latest row. WHO may make which transition is decided by
-- the app from the form's RACI (src/lib/docs/lifecycle.ts); the database
-- guarantees the row is the caller's own, on the caller's own team, and
-- never rewritten.
--
-- WHO SEES WHAT. Team members insert and read their team's rows; instructors
-- and admins read every team's. NOBODY updates or deletes — history is
-- history (trigger below, the 0009 pattern). Deletes stay possible for
-- `on delete cascade` when an account is erased.
--
-- All policies use the 0006 definer helpers — never a subquery on
-- memberships/profiles (the recursion 0006 fixed; guarded).
--
-- Idempotent for the same reason as 0001–0011.

create table if not exists public.deliverable_status (
  id uuid primary key default gen_random_uuid(),
  course_id text not null,
  team_id text not null,
  deliverable_id text not null,
  status text not null check (status in ('draft', 'in_review', 'approved', 'issued')),
  changed_by uuid not null references auth.users(id) on delete cascade,
  role text not null,
  note text not null default '',
  version int not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists deliverable_status_team_idx on public.deliverable_status (course_id, team_id, deliverable_id, created_at);
alter table public.deliverable_status enable row level security;

drop policy if exists "status team insert"     on public.deliverable_status;
drop policy if exists "status team read"       on public.deliverable_status;
drop policy if exists "status instructor read" on public.deliverable_status;

create policy "status team insert" on public.deliverable_status for insert
  with check (changed_by = auth.uid() and public.on_team(course_id, team_id));
create policy "status team read" on public.deliverable_status for select
  using (public.on_team(course_id, team_id));
create policy "status instructor read" on public.deliverable_status for select
  using (public.is_instructor());

-- Append-only, enforced below RLS too: a new state is a new row.
create or replace function public.forbid_status_update()
returns trigger language plpgsql as $$
begin
  raise exception 'deliverable_status is append-only — record a new transition instead';
end $$;
drop trigger if exists deliverable_status_immutable on public.deliverable_status;
create trigger deliverable_status_immutable
  before update on public.deliverable_status
  for each row execute function public.forbid_status_update();

-- Realtime: a teammate's approval or return reaches the form live.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'deliverable_status') then
    execute 'alter publication supabase_realtime add table public.deliverable_status';
  end if;
end $$;
