-- Capstone Quarry — complete database setup, in one file.
--
-- WHAT THIS IS
--   Every migration from supabase/migrations/, concatenated in order. Paste the
--   whole file into the Supabase dashboard once:
--
--     SQL Editor (left sidebar)  →  New query  →  paste  →  Run
--
--   Expect "Success. No rows returned." That is what success looks like for
--   statements that create things rather than select them.
--
-- WHEN TO RUN IT
--   Before the first person signs in. This installs the trigger that creates a
--   profile row for each new account; an account made before that trigger exists
--   will have no profile, and the fix is to delete the user and sign in again.
--
-- SAFE TO RE-RUN
--   Every statement is idempotent (if not exists / or replace / drop-then-create),
--   so running it twice changes nothing.
--
-- DO NOT EDIT THIS FILE
--   It is generated. Edit the files in supabase/migrations/ and re-run:
--       python3 scripts/build-setup-sql.py


-- ─── 0001_init.sql ────────────────────

-- 0001_init.sql — accounts, roster, progress and team artifacts.
--
-- This is the schema that used to live only inside SUPABASE_SETUP.md as a block
-- to copy-paste. It is the same schema, made **idempotent** so it can be re-run
-- safely: some projects were set up by pasting the markdown by hand, and a
-- second run must be a no-op rather than an error.
--
-- Every table is row-level secured. The rules, in one sentence each:
--   profiles          — you read/write your own; teammates may read your name.
--   memberships       — you write your own; anyone on the course may read it.
--   step_completions  — you write your own; teammates may read yours.
--   deliverables      — the whole team reads and writes (shared documents).
--   gate_status       — same as deliverables.
-- Instructors may additionally read (never write) the first four.

-- ── 1. profiles (1:1 with auth.users) ────────────────────────────────────────
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  is_instructor boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

drop policy if exists "profiles self read"      on public.profiles;
drop policy if exists "profiles self update"    on public.profiles;
drop policy if exists "profiles self insert"    on public.profiles;
drop policy if exists "profiles teammates read" on public.profiles;

create policy "profiles self read"   on public.profiles for select using (auth.uid() = id);
create policy "profiles self update" on public.profiles for update using (auth.uid() = id);
create policy "profiles self insert" on public.profiles for insert with check (auth.uid() = id);
-- teammates may read each other's display name
create policy "profiles teammates read" on public.profiles for select using (
  exists (select 1 from public.memberships m1
          join public.memberships m2
            on m1.course_id = m2.course_id and m1.team_id = m2.team_id
          where m1.user_id = auth.uid() and m2.user_id = profiles.id)
);

-- auto-create a profile row on signup, so the app never has to.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email))
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users for each row execute function public.handle_new_user();

-- ── 2. memberships (roster). user_id replaces the old synthesized memberId ───
create table if not exists public.memberships (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  team_id text not null,
  role text not null,
  display_name text not null,
  cohort text not null,
  joined_at timestamptz not null default now(),
  primary key (user_id, course_id)              -- one team per user per course
);
alter table public.memberships enable row level security;

drop policy if exists "memberships self write"  on public.memberships;
drop policy if exists "memberships course read" on public.memberships;

create policy "memberships self write" on public.memberships for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "memberships course read" on public.memberships for select using (
  exists (select 1 from public.memberships me
          where me.user_id = auth.uid() and me.course_id = memberships.course_id)
);

-- ── 3. step_completions ──────────────────────────────────────────────────────
create table if not exists public.step_completions (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  task_id text not null,
  step_id text not null,
  completed_at timestamptz not null default now(),
  primary key (user_id, course_id, task_id, step_id)
);
alter table public.step_completions enable row level security;

drop policy if exists "completions self write"     on public.step_completions;
drop policy if exists "completions teammates read" on public.step_completions;

create policy "completions self write" on public.step_completions for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "completions teammates read" on public.step_completions for select using (
  exists (select 1 from public.memberships me
          join public.memberships them
            on me.course_id = them.course_id and me.team_id = them.team_id
          where me.user_id = auth.uid()
            and them.user_id = step_completions.user_id
            and them.course_id = step_completions.course_id)
);

-- ── 4. deliverables (team-scoped form data) ──────────────────────────────────
create table if not exists public.deliverables (
  course_id text not null,
  team_id text not null,
  deliverable_id text not null,
  data jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  primary key (course_id, team_id, deliverable_id)
);
alter table public.deliverables enable row level security;

drop policy if exists "deliverables team rw" on public.deliverables;

create policy "deliverables team rw" on public.deliverables for all
  using (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = deliverables.course_id
                   and me.team_id = deliverables.team_id))
  with check (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = deliverables.course_id
                   and me.team_id = deliverables.team_id));

-- ── 5. gate_status (team-scoped) ─────────────────────────────────────────────
create table if not exists public.gate_status (
  course_id text not null,
  team_id text not null,
  gate_id int not null,
  status text not null check (status in ('locked','ready','passed')),
  updated_at timestamptz not null default now(),
  primary key (course_id, team_id, gate_id)
);
alter table public.gate_status enable row level security;

drop policy if exists "gate team rw" on public.gate_status;

create policy "gate team rw" on public.gate_status for all
  using (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = gate_status.course_id
                   and me.team_id = gate_status.team_id))
  with check (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = gate_status.course_id
                   and me.team_id = gate_status.team_id));

-- ── Instructor read-only access (for a future dashboard) ─────────────────────
drop policy if exists "instructor reads memberships"  on public.memberships;
drop policy if exists "instructor reads completions"  on public.step_completions;
drop policy if exists "instructor reads deliverables" on public.deliverables;

create policy "instructor reads memberships"  on public.memberships      for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));
create policy "instructor reads completions"  on public.step_completions for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));
create policy "instructor reads deliverables" on public.deliverables     for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── Realtime: stream teammates' changes ──────────────────────────────────────
-- `add table` errors if the table is already in the publication, so each is
-- guarded. Wrapped individually so one already-added table doesn't abort the rest.
do $$
declare t text;
begin
  foreach t in array array['step_completions','deliverables','memberships','gate_status'] loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', t);
    exception when duplicate_object then null;
    end;
  end loop;
end $$;

-- ─── 0002_student_state.sql ────────────────────

-- 0002_student_state.sql — the student data that had no cloud path.
--
-- Before this, four things lived only in localStorage, so a student who changed
-- browser or device silently lost them: where they left off, the Week-0
-- acknowledgement, their GRC registers, and their lab access details.
--
-- Each payload is already a self-contained JSON object in the app, so each table
-- stores one `data jsonb` rather than a column per field. That keeps these
-- migrations stable when a field is added to the shape later — which has
-- happened to all three at least once already.
--
-- Idempotent for the same reason as 0001.

-- ── user_course_state — resume pointer + per-course acknowledgements ─────────
-- Shape of `data`:
--   { "resume": { "week": 2, "taskId": "cb-w2", "stepId": "cb-w2-s1", "at": 172… },
--     "homeBuildAck": true }
-- Owner-only: this is a private UI pointer, of no interest to anyone else.
create table if not exists public.user_course_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, course_id)
);
alter table public.user_course_state enable row level security;

drop policy if exists "user state self rw" on public.user_course_state;

create policy "user state self rw" on public.user_course_state for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── grc_registers — team-scoped GRC workspace ───────────────────────────────
-- Team-shared like `deliverables`, and deliberately using the identical
-- membership-join policy so the two behave the same way.
create table if not exists public.grc_registers (
  course_id text not null,
  team_id text not null,
  data jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  primary key (course_id, team_id)
);
alter table public.grc_registers enable row level security;

drop policy if exists "grc team rw" on public.grc_registers;

create policy "grc team rw" on public.grc_registers for all
  using (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = grc_registers.course_id
                   and me.team_id = grc_registers.team_id))
  with check (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = grc_registers.course_id
                   and me.team_id = grc_registers.team_id));

-- ── lab_access — the student's own lab IPs, credentials and checklist ────────
-- Shape of `data`: { "values": {...}, "checks": {...}, "notes": "..." }
--
-- STRICTLY OWNER-ONLY. This is the one table in the schema that teammates
-- CANNOT read and that instructors CANNOT read, because the `notes` field
-- explicitly invites students to record lab passwords. There is no teammate
-- policy and no instructor policy here, and that omission is deliberate — do not
-- "make it consistent" with the tables above.
create table if not exists public.lab_access (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, course_id)
);
alter table public.lab_access enable row level security;

drop policy if exists "lab access self rw" on public.lab_access;

create policy "lab access self rw" on public.lab_access for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- Only the team-shared table needs to stream: the other two are single-user, so
-- there is no second party to notify, and publishing lab_access would put
-- credentials on a realtime channel for no benefit.
do $$
begin
  begin
    execute 'alter publication supabase_realtime add table public.grc_registers';
  exception when duplicate_object then null;
  end;
end $$;

-- ─── 0003_evidence_ledger.sql ────────────────────

-- 0003_evidence_ledger.sql — persist the proof of work the app already computes.
--
-- Until now a "completed" capstone was a column of self-ticked checkboxes. The
-- app computed real signals and then threw every one of them away:
--   * the student's pasted command output and whether it matched the step's
--     `verify` tokens — React state in OutputVerify, gone on unmount;
--   * the SHA-256 of each real evidence file — computed in EvidenceHasher and
--     WeekEvidencePackager, then copied to the clipboard or into a downloaded
--     zip and forgotten.
--
-- These three tables keep those signals. Together they are the difference
-- between "the student says they did it" and "here is a hashed, timestamped
-- record of what they produced" — see docs/adr/0004-content-addressed-evidence.md
-- ("self-study keeps files local; the hash + custody record is what the platform
-- owns") and ROADMAP.md Phase 1.
--
-- WHAT THIS DOES NOT CLAIM. `step_evidence` records that output matching the
-- expected tokens was pasted, hashed and timestamped by this account. It is not
-- proof a command truly ran on a real machine — the check is client-side and a
-- determined student can defeat it. It is honest self-verification with an audit
-- trail, and the UI wording must say exactly that and no more. State-reading
-- validators (roadmap Phase 2) are what would make it proof.
--
-- PRIVACY. We deliberately store the SHA-256 of the pasted output and the match
-- counts, never the raw terminal text: that text routinely carries internal IPs,
-- hostnames and sometimes credentials. The hash is still tamper-evident — ask a
-- student to re-produce the output and it must hash identically — while the
-- platform never holds the sensitive bytes. Raw text stays in the browser.
--
-- Idempotent for the same reason as 0001 and 0002.

-- ── step_evidence — per-step verification record ─────────────────────────────
-- One row per (student, step). `method` distinguishes the two ways a step can be
-- finished, which is the single most useful fact on the whole dashboard:
--   'verified-output' — pasted output contained every `verify` token
--   'self-attested'   — the student ticked the box; no matching output
--   'file-hash'       — completion evidenced by a hashed artifact
-- `attempts` counts pastes, so a step solved on the fifth try is visible as real
-- troubleshooting rather than being flattened to a tick. Effort is MEASURED AND
-- NEVER REWARDED — the rubric is not speed (see ARCHITECTURE.md §3).
--
-- Owner-only, like user_course_state. No teammate or instructor policy: this
-- round the student's verification record is private to them and leaves only via
-- the portfolio export they choose to generate.
create table if not exists public.step_evidence (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  task_id text not null,
  step_id text not null,
  verified boolean not null default false,
  method text not null default 'self-attested'
    check (method in ('verified-output', 'self-attested', 'file-hash')),
  matched_tokens int not null default 0,
  total_tokens int not null default 0,
  output_sha256 text,
  attempts int not null default 0,
  first_attempt_at timestamptz,
  verified_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, course_id, task_id, step_id)
);
alter table public.step_evidence enable row level security;

drop policy if exists "step evidence self rw" on public.step_evidence;

create policy "step evidence self rw" on public.step_evidence for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── evidence_artifacts — the content-addressed custody record ────────────────
-- Keyed by the hash itself, so re-hashing the same file is idempotent and the
-- same artifact can never be double-counted. The FILE IS NOT STORED — only its
-- hash, name, size and where it belongs. That is the whole point of ADR-0004 for
-- self-study: the student keeps the pcap, the platform keeps the proof it
-- existed, unchanged, at a point in time.
--
-- `name_ok` records whether the filename matched the course convention
-- (YYYYMMDD_TeamXX_Tool_Action.ext, validateEvidenceFileName in src/lib/utils.ts)
-- at the moment of hashing, so evidence-naming compliance is measurable.
create table if not exists public.evidence_artifacts (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  sha256 text not null,
  filename text not null,
  size_bytes bigint not null default 0,
  week int,
  deliverable_id text,
  name_ok boolean not null default false,
  hashed_at timestamptz not null default now(),
  primary key (user_id, course_id, sha256)
);
alter table public.evidence_artifacts enable row level security;

drop policy if exists "evidence artifacts self rw" on public.evidence_artifacts;

create policy "evidence artifacts self rw" on public.evidence_artifacts for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── user_paths — the career track the student is working toward ──────────────
-- The first genuinely GLOBAL per-user row in the schema: a path spans courses
-- (Security+ → CySA+ → CISSP), so unlike every other student table it is not
-- course-scoped. Note for whoever adds the next one: hydrateCourse() in
-- src/lib/data/supabaseCache.ts filters every query by course_id and therefore
-- cannot fetch this. It is loaded by hydrateUser() instead.
create table if not exists public.user_paths (
  user_id uuid primary key references auth.users(id) on delete cascade,
  path_id text not null,
  chosen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.user_paths enable row level security;

drop policy if exists "user path self rw" on public.user_paths;

create policy "user path self rw" on public.user_paths for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- Deliberately nothing here. All three tables are single-user, so there is no
-- second party to notify, and streaming a student's verification record would
-- put their evidence on a channel for no benefit — the same reasoning that keeps
-- lab_access unpublished in 0002.

-- ─── 0004_cohort_review_notes.sql ────────────────────

-- 0004_cohort_review_notes.sql — the R68 round: an instructor can see and
-- judge the cohort, a cohort has dates, and a student can keep notes on a step
-- and say "I'm stuck" where the team can see it.
--
-- WHAT THIS WIDENS. 0001 already lets an instructor read memberships,
-- step_completions and deliverables. The cohort dashboard also needs the
-- evidence ledger (verified-vs-self-attested is the single most useful column
-- it shows) and gate status, so those gain the same read-only policy. Reads
-- only, and 0003's privacy note still holds: the ledger carries hashes and
-- counts, never pasted text.
--
-- TWO TABLES FOR NOTES, ON PURPOSE. A student's note is private (like
-- lab_access: no teammate or instructor policy). The one bit of it teammates
-- and the instructor may see is that they are stuck. RLS is row-level, so a
-- column that must hide from teammates cannot live in a row they may read —
-- hence `step_notes` (owner-only) and `step_flags` (team + instructor read).
-- The app writes both from one save and presents one record.
--
-- Idempotent for the same reason as 0001–0003.

-- ── Instructor reads the ledger and gates ────────────────────────────────────
drop policy if exists "instructor reads step evidence" on public.step_evidence;
drop policy if exists "instructor reads artifacts"     on public.evidence_artifacts;
drop policy if exists "instructor reads gates"         on public.gate_status;

create policy "instructor reads step evidence" on public.step_evidence      for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));
create policy "instructor reads artifacts"     on public.evidence_artifacts for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));
create policy "instructor reads gates"         on public.gate_status        for select using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── deliverable_reviews — one verdict per (team, form, week) ────────────────
create table if not exists public.deliverable_reviews (
  course_id text not null,
  team_id text not null,
  deliverable_id text not null,
  week int not null,
  status text not null check (status in ('approved', 'revise', 'pending')),
  comment text not null default '',
  reviewer text not null default '',
  reviewer_id uuid references auth.users(id),
  reviewed_at timestamptz not null default now(),
  primary key (course_id, team_id, deliverable_id, week)
);
alter table public.deliverable_reviews enable row level security;

drop policy if exists "reviews team read"       on public.deliverable_reviews;
drop policy if exists "reviews instructor all"  on public.deliverable_reviews;

create policy "reviews team read" on public.deliverable_reviews for select
  using (exists (select 1 from public.memberships me
                 where me.user_id = auth.uid()
                   and me.course_id = deliverable_reviews.course_id
                   and me.team_id = deliverable_reviews.team_id));
create policy "reviews instructor all" on public.deliverable_reviews for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── cohorts — the one date everything is derived from ────────────────────────
create table if not exists public.cohorts (
  course_id text not null,
  cohort text not null,
  starts_on date not null,
  set_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  primary key (course_id, cohort)
);
alter table public.cohorts enable row level security;

drop policy if exists "cohorts anyone reads"     on public.cohorts;
drop policy if exists "cohorts instructor writes" on public.cohorts;

create policy "cohorts anyone reads" on public.cohorts for select using (auth.uid() is not null);
create policy "cohorts instructor writes" on public.cohorts for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── step_notes — OWNER-ONLY, like lab_access ─────────────────────────────────
create table if not exists public.step_notes (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  task_id text not null,
  step_id text not null,
  note text not null default '',
  updated_at timestamptz not null default now(),
  primary key (user_id, course_id, task_id, step_id)
);
alter table public.step_notes enable row level security;

drop policy if exists "step_notes self rw" on public.step_notes;
create policy "step_notes self rw" on public.step_notes for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── step_flags — the shareable half ──────────────────────────────────────────
create table if not exists public.step_flags (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  task_id text not null,
  step_id text not null,
  stuck boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, course_id, task_id, step_id)
);
alter table public.step_flags enable row level security;

drop policy if exists "step_flags self rw"         on public.step_flags;
drop policy if exists "step_flags team read"       on public.step_flags;
drop policy if exists "step_flags instructor read" on public.step_flags;

create policy "step_flags self rw" on public.step_flags for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "step_flags team read" on public.step_flags for select
  using (exists (select 1 from public.memberships me
                 join public.memberships them on them.course_id = me.course_id and them.team_id = me.team_id
                 where me.user_id = auth.uid()
                   and them.user_id = step_flags.user_id
                   and me.course_id = step_flags.course_id));
create policy "step_flags instructor read" on public.step_flags for select
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- Reviews reach the team, flags reach the team, a cohort date reaches the class.
-- step_notes is deliberately absent: owner-only data has no second party.
do $$
declare t text;
begin
  foreach t in array array['deliverable_reviews','step_flags','cohorts'] loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', t);
    exception when duplicate_object then null;
    end;
  end loop;
end $$;

-- ─── 0005_course_documents.sql ────────────────────

-- 0005_course_documents.sql — the R78-D round: the course document has a table.
--
-- WHAT THIS ADDS. Every table before this one holds student state; course
-- CONTENT — the seeds and anything an instructor authored in the studio — lived
-- only in the browser's localStorage, so an authored course existed on one
-- device. `course_documents` holds one row per course: the whole document the
-- app renders from (`content/courses/<id>.json` has the same shape), keyed by
-- course id. A row with a seed's id overrides that seed, which is how the studio
-- already worked locally.
--
-- WHO SEES IT. Any signed-in user reads (the catalogue and the course pages
-- need it); only an instructor writes, using the predicate 0004 established
-- for `deliverable_reviews` and `cohorts`.
--
-- TWO REPAIRS, while a migration is open:
--   * `step_evidence.method` allowed 'file-hash', a value the app never wrote —
--     `EvidenceMethod` is 'verified-output' | 'self-attested'. The CHECK now
--     says what the type says.
--   * `grc_registers` had no reader and no writer in the app (its localStorage
--     key was never used either), only a realtime subscription. Dropped.
--
-- Idempotent for the same reason as 0001–0004.

-- ── course_documents — one row per course, the document the app renders ─────
create table if not exists public.course_documents (
  course_id text primary key,
  schema text not null,
  doc jsonb not null,
  version int not null default 1,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);
alter table public.course_documents enable row level security;

drop policy if exists "course documents signed-in read"    on public.course_documents;
drop policy if exists "course documents instructor writes" on public.course_documents;

create policy "course documents signed-in read" on public.course_documents for select
  using (auth.uid() is not null);
create policy "course documents instructor writes" on public.course_documents for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_instructor));

-- ── step_evidence.method — the CHECK matches EvidenceMethod ─────────────────
alter table public.step_evidence drop constraint if exists step_evidence_method_check;
alter table public.step_evidence
  add constraint step_evidence_method_check check (method in ('verified-output', 'self-attested'));

-- ── grc_registers — nothing reads it, nothing writes it ─────────────────────
-- Dropping the table removes it from the realtime publication as well.
drop table if exists public.grc_registers;

-- ── Realtime ─────────────────────────────────────────────────────────────────
-- A course an instructor publishes or edits should reach every open client.
do $$
begin
  begin
    execute 'alter publication supabase_realtime add table public.course_documents';
  exception when duplicate_object then null;
  end;
end $$;
