#!/usr/bin/env python3
"""Build supabase/setup.sql — every migration in one file, to be pasted once.

Why this file exists
--------------------
Setting the platform up meant opening `supabase/migrations/`, then running three
files in the SQL Editor in the right order. That is three chances to paste the
wrong thing, run them out of order, or stop after the first one — and a half-run
schema fails later, at sign-in, far from the mistake that caused it.

`supabase/migrations/` stays the source of truth: it is what a real migration
runner (`supabase db push`) consumes, and each file is a numbered step in the
project's history. This generator flattens those same files, in order, into ONE
artifact whose only job is to be pasted into the dashboard's SQL Editor by a
person setting the project up by hand.

Nothing is rewritten — the migration bodies are copied verbatim, so the flattened
file and the migrations cannot say different things. `src/lib/setupSql.test.ts`
asserts exactly that, so editing a migration without re-running this fails CI.

    python3 scripts/build-setup-sql.py

Standard library only — no new dependency.
"""

from pathlib import Path
import sys

REPO = Path(__file__).resolve().parent.parent
MIGRATIONS = REPO / "supabase" / "migrations"
OUT = REPO / "supabase" / "setup.sql"

# The marker the drift guard and this generator agree on. Kept short so the
# generated file still reads as ordinary SQL.
BANNER = "-- ─── {name} " + "─" * 20

HEADER = """\
-- Capstone Quarry — complete database setup, in one file.
--
-- WHAT THIS IS
--   Every migration from supabase/migrations/, concatenated in order. Paste the
--   whole file into the Supabase dashboard once:
--
--     SQL Editor (left sidebar)  →  New query  →  paste  →  Run
--
--   Expect "Success. No rows returned." That is what success looks like for
--   statements that create things rather than select them.
--
-- WHEN TO RUN IT
--   Before the first person signs in. This installs the trigger that creates a
--   profile row for each new account; an account made before that trigger exists
--   will have no profile, and the fix is to delete the user and sign in again.
--
-- SAFE TO RE-RUN
--   Every statement is idempotent (if not exists / or replace / drop-then-create),
--   so running it twice changes nothing.
--
-- DO NOT EDIT THIS FILE
--   It is generated. Edit the files in supabase/migrations/ and re-run:
--       python3 scripts/build-setup-sql.py
"""


def build() -> None:
    files = sorted(MIGRATIONS.glob("*.sql"))
    if not files:
        sys.exit(f"no migrations found in {MIGRATIONS}")

    parts = [HEADER]
    for path in files:
        body = path.read_text(encoding="utf-8").strip("\n")
        parts.append(BANNER.format(name=path.name))
        parts.append(body)

    text = "\n\n".join(parts) + "\n"
    OUT.write_text(text, encoding="utf-8")

    # The generated file is worthless if it is missing a migration's content, so
    # prove every body survived the concatenation before claiming success.
    written = OUT.read_text(encoding="utf-8")
    for path in files:
        body = path.read_text(encoding="utf-8").strip("\n")
        if body not in written:
            sys.exit(f"{path.name} did not survive concatenation")
        if BANNER.format(name=path.name) not in written:
            sys.exit(f"{path.name} banner missing")

    print(f"wrote {OUT.relative_to(REPO)} ({OUT.stat().st_size:,} bytes)")
    for path in files:
        n = len(path.read_text(encoding='utf-8').splitlines())
        print(f"  {n:>4} lines  {path.name}")
    print(f"  {len(written.splitlines()):>4} lines  total")


if __name__ == "__main__":
    build()
